(function(){
 const KEY='careerNavigationWork24ResultsV3';
 const SELF_KEY='careerNavigationSelfAwarenessV4';
 const URL='https://www.work24.go.kr/wk/r/c/1000/jobPsyExamList.do';
 const RIASEC=[['R','현실형'],['I','탐구형'],['A','예술형'],['S','사회형'],['E','진취형'],['C','관습형']];
 const INTEREST_LABEL={R:'직접 만들고 움직이기',I:'분석하고 탐구하기',A:'표현하고 창작하기',S:'돕고 가르치기',E:'설득하고 이끌기',C:'정리하고 체계화하기'};
 const VALUES=['일과 삶의 균형','직업안정','경제적 보상','성취','사회적 인정','자율성','변화지향','자기개발','사회적 공헌'];
 const VALUE_MAP={'일과 삶의 균형':['워라밸'],'직업안정':['안정'],'경제적 보상':['보상'],'성취':['성취'],'사회적 인정':['인정'],'자율성':['자율성'],'변화지향':['도전','성장','창의성'],'자기개발':['성장','학습기회','전문성'],'사회적 공헌':['사회기여','일의 의미']};
 const READINESS=[
  ['진로성숙도',[['planning','계획성'],['independence','독립성'],['selfKnowledge','자신지식(자기이해)']]],
  ['진로탐색행동',[['careerActivityExperience','진로활동경험'],['selfUnderstandingEffort','자기이해노력'],['careerClassActivity','진로수업활동'],['socialSupport','사회적 지지자 지원']]],
  ['진로의사결정',[['careerDecision','진로의사결정']]],
  ['취업준비행동',[['activeJobSearch','적극적 직업탐색'],['informalJobSearch','비공식적 직업탐색'],['preliminaryJobSearch','예비적 직업탐색'],['formalJobSearch','공식적 직업탐색'],['employmentPreparationEffort','취업준비노력'],['employmentPreparationIntensity','취업준비강도']]]
 ];
 let active='riasec',backStep=null,nextStep=null,state=read();
 function blank(){return{riasec:{scores:{},status:'draft',completedAt:''},workvalue:{topValues:[],status:'draft',completedAt:''},careerreadiness:{scores:{},status:'draft',completedAt:''}}}
 function read(){const b=blank();try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(x.riasec)b.riasec={...b.riasec,...x.riasec,scores:{...(x.riasec.scores||{})}};if(x.workvalue){b.workvalue={...b.workvalue,...x.workvalue,topValues:Array.isArray(x.workvalue.topValues)?x.workvalue.topValues.slice(0,5):[]};if(!b.workvalue.topValues.length&&x.workvalue.scores){const old=Object.entries(x.workvalue.scores).filter(([,v])=>v!==''&&v!=null).map(([value,score])=>({value,score:Number(score)})).sort((a,b)=>b.score-a.score).slice(0,5);b.workvalue.topValues=old}}if(x.careerreadiness)b.careerreadiness={...b.careerreadiness,...x.careerreadiness,scores:{...(x.careerreadiness.scores||{})}}}catch(e){}return b}
 function save(){localStorage.setItem(KEY,JSON.stringify(state))}
 function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function num(v){if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
 function selfInterest(){try{const x=JSON.parse(localStorage.getItem(SELF_KEY)||'{}');return Array.isArray(x.interest?.selected)?x.interest.selected:[]}catch(e){return[]}}
 function qualitativeValues(){try{return Array.isArray(window.selectedValues)?window.selectedValues:[]}catch(e){return[]}}
 function title(id){return id==='riasec'?'직업선호도검사 S형(개정)':id==='workvalue'?'성인용 직업가치관검사':'대학생 진로준비도검사'}
 function stepNo(id){return id==='riasec'?2:id==='workvalue'?4:10}
 function setApp(v){if(typeof window.setCareerAppVisibleV3==='function')window.setCareerAppVisibleV3(v);else{const main=document.querySelector('.wrap > main');if(main)main.style.display=v?'':'none'}}
 function ensureStyle(){if(document.getElementById('work24V4Style'))return;const s=document.createElement('style');s.id='work24V4Style';s.textContent=`.work24V4Hidden{display:none!important}.work24V4{background:#fff;border:1px solid var(--line);border-radius:24px;padding:22px;margin:14px 0;box-shadow:0 8px 24px rgba(26,38,68,.05)}.w4Head{text-align:center;max-width:800px;margin:0 auto 15px}.w4Head span{display:inline-block;font-size:10px;font-weight:900;letter-spacing:.08em;color:#1658a7;background:#edf6ff;border-radius:999px;padding:6px 9px}.w4Head h2{font-size:26px;margin:11px 0 7px}.w4Head p{color:var(--muted);line-height:1.6;margin:0}.w4Guide{display:flex;justify-content:space-between;align-items:center;gap:12px;border:1px solid var(--line);border-radius:17px;padding:14px;background:#fbfcff}.w4Guide h3{margin:0 0 4px}.w4Steps{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:12px 0}.w4Steps span{border:1px solid var(--line);border-radius:11px;padding:8px;background:#fff;text-align:center;font-size:11px;color:#56627a}.w4Grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:13px}.w4Field{display:grid;grid-template-columns:1fr 86px;gap:8px;align-items:center;border:1px solid var(--line);border-radius:13px;background:#fff;padding:10px}.w4Field b{font-size:12px}.w4Field input{padding:9px;text-align:center}.w4ValueRow{display:grid;grid-template-columns:46px 1fr 95px;gap:8px;align-items:center;margin:8px 0}.w4Rank{width:40px;height:40px;border-radius:12px;background:#eef0ff;color:#4b42c2;display:grid;place-items:center;font-weight:900}.w4Compare{border:1px solid #d8d5ff;background:#f8f7ff;border-radius:16px;padding:14px;margin-top:14px}.w4Compare h3{margin:0 0 8px;font-size:17px}.w4CompareGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.w4CompareBox{background:#fff;border:1px solid var(--line);border-radius:13px;padding:11px}.w4CompareBox b{font-size:12px}.w4Common{margin-top:10px;color:#315c46;background:#f3fbf6;border:1px solid #d7e9df;border-radius:12px;padding:10px;font-size:12px}.w4Group{border-top:1px solid var(--line);margin-top:13px;padding-top:12px}.w4Group h4{margin:0}.w4Actions{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:16px}.w4Actions>div{display:flex;gap:8px}@media(max-width:720px){.w4Grid{grid-template-columns:1fr 1fr}.w4Steps{grid-template-columns:1fr 1fr}.w4Guide{align-items:stretch;flex-direction:column}.w4Guide .btn{width:100%}.w4CompareGrid{grid-template-columns:1fr}.w4Actions{align-items:stretch;flex-direction:column}.w4Actions>div{display:grid;grid-template-columns:1fr;width:100%}.w4Actions .btn{width:100%}}@media(max-width:480px){.w4Grid{grid-template-columns:1fr}.w4ValueRow{grid-template-columns:38px 1fr 82px}.work24V4{padding:16px}}`;document.head.appendChild(s)}
 function ensure(){let s=document.getElementById('work24V4');if(!s){s=document.createElement('section');s.id='work24V4';const mode=document.getElementById('courseModeScreenV3'),hero=document.querySelector('.hero');if(mode&&mode.parentNode)mode.parentNode.insertBefore(s,mode.nextSibling);else hero?.insertAdjacentElement('afterend',s)}return s}
 function riasecTop(){return RIASEC.map(([id,label])=>({id,label,score:num(state.riasec.scores[id])})).filter(x=>x.score!==null).sort((a,b)=>b.score-a.score).slice(0,3)}
 function riasecCompare(){const mine=selfInterest().slice(0,3),test=riasecTop();if(test.length<3)return'';const common=mine.filter(id=>test.some(x=>x.id===id));return `<div class="w4Compare"><h3>내가 생각한 흥미 ↔ 고용24 검사 결과</h3><div class="w4CompareGrid"><div class="w4CompareBox"><b>검사 전 · 내가 생각한 TOP3</b><div class="pillbox">${mine.map((id,i)=>`<span class="pill">${i+1}. ${esc(INTEREST_LABEL[id]||id)}</span>`).join('')||'<span class="muted">미입력</span>'}</div></div><div class="w4CompareBox"><b>고용24 · RIASEC TOP3</b><div class="pillbox">${test.map((x,i)=>`<span class="pill via">${i+1}. ${x.id} ${esc(x.label)} · ${x.score}</span>`).join('')}</div></div></div><div class="w4Common"><b>공통으로 나타난 흥미</b> · ${common.length?common.map(id=>INTEREST_LABEL[id]).join(' · '):'TOP3에서 바로 겹치는 항목은 없습니다. 차이가 왜 생겼는지 생각해보세요.'}</div></div>`}
 function valueCompare(){const top=state.workvalue.topValues.filter(x=>x.value&&num(x.score)!==null);if(top.length<3)return'';const mine=qualitativeValues().slice(0,5);const matches=top.filter(x=>(VALUE_MAP[x.value]||[]).some(v=>mine.includes(v)));return `<div class="w4Compare"><h3>내가 중요하다고 생각한 가치 ↔ 고용24 결과</h3><div class="w4CompareGrid"><div class="w4CompareBox"><b>검사 전 · 내가 선택한 가치</b><div class="pillbox">${mine.map(x=>`<span class="pill">${esc(typeof valueLabel==='function'?valueLabel(x):x)}</span>`).join('')||'<span class="muted">미입력</span>'}</div></div><div class="w4CompareBox"><b>고용24 · 상위 직업가치</b><div class="pillbox">${top.map((x,i)=>`<span class="pill via">${i+1}. ${esc(x.value)} · ${x.score}</span>`).join('')}</div></div></div><div class="w4Common"><b>비슷하게 나타난 가치</b> · ${matches.length?matches.map(x=>x.value).join(' · '):'직접 선택한 가치와 검사 상위가치가 다르게 나타났습니다. 어느 쪽이 더 실제 선택에 가까운지 생각해보세요.'}</div></div>`}
 function riasecPanel(){return `<div class="w4Grid">${RIASEC.map(([id,label])=>`<label class="w4Field"><b>${id} · ${label}</b><input type="number" min="0" max="100" step="1" value="${esc(state.riasec.scores[id]??'')}" placeholder="표준점수" oninput="updateWork24V4Score('riasec','${id}',this.value)"></label>`).join('')}</div><div class="small muted" style="margin-top:9px">결과표의 <b>표준점수</b> 6개를 입력합니다. 원점수가 아닙니다.</div>${riasecCompare()}`}
 function valueRows(){const rows=Array.from({length:5},(_,i)=>state.workvalue.topValues[i]||{value:'',score:''});return rows.map((r,i)=>`<div class="w4ValueRow"><div class="w4Rank">${i+1}</div><select onchange="updateWork24V4Value(${i},'value',this.value)"><option value="">${i<3?'선택 필수':'선택사항'}</option>${VALUES.map(v=>`<option value="${esc(v)}" ${r.value===v?'selected':''}>${esc(v)}</option>`).join('')}</select><input type="number" min="0" max="100" step="1" value="${esc(r.score??'')}" placeholder="점수" oninput="updateWork24V4Value(${i},'score',this.value)"></div>`).join('')}
 function valuePanel(){return `<div class="callout"><b>TOP5 입력을 권장합니다.</b><br>연구 활용을 위해 최소 TOP3의 <b>가치명과 점수</b>를 입력하고, 결과표에 쉽게 확인할 수 있다면 4·5위까지 입력하세요. 9개 전체를 다시 옮겨 적을 필요는 없습니다.</div>${valueRows()}${valueCompare()}`}
 function readinessPanel(){return READINESS.map(([g,fields])=>`<div class="w4Group"><h4>${esc(g)}</h4><div class="w4Grid">${fields.map(([k,l])=>`<label class="w4Field"><b>${esc(l)}</b><input type="number" min="0" max="100" step="1" value="${esc(state.careerreadiness.scores[k]??'')}" placeholder="T점수" oninput="updateWork24V4Score('careerreadiness','${k}',this.value)"></label>`).join('')}</div></div>`).join('')+`<div class="small muted" style="margin-top:10px">결과표의 각 하위요인 <b>T점수</b>를 그대로 입력합니다.</div>`}
 function panel(){return active==='riasec'?riasecPanel():active==='workvalue'?valuePanel():readinessPanel()}
 function render(){state=read();const s=ensure();s.className='work24V4';s.innerHTML=`<div class="w4Head"><span>STEP ${stepNo(active)} · WORK24</span><h2>${title(active)}</h2><p>고용24에서 공식검사를 실시한 뒤 Career Navigation에는 필요한 결과만 입력합니다.</p></div><div class="w4Guide"><div><h3>고용24에서 검사 먼저 실시</h3><div class="small muted">검사문항과 개인정보는 이 앱으로 가져오지 않습니다.</div></div><a class="btn btnPrimary" href="${URL}" target="_blank" rel="noopener">고용24 검사실시 화면 열기 ↗</a></div><div class="w4Steps"><span>① 고용24 로그인</span><span>② ${title(active)} 찾기</span><span>③ 검사 실시</span><span>④ 결과 입력·비교</span></div>${panel()}<div class="w4Actions"><button type="button" class="btn btnSecondary" onclick="backWork24V4()">← 이전 단계</button><div><button type="button" class="btn btnOutline" onclick="skipWork24V4()">나중에 입력</button><button type="button" class="btn btnPrimary" onclick="saveAndNextWork24V4()">결과 저장 · 다음 →</button></div></div>`;window.scrollTo({top:0,behavior:'smooth'})}
 function validate(){if(active==='riasec'){const miss=RIASEC.filter(([id])=>num(state.riasec.scores[id])===null);if(miss.length){alert('RIASEC 6개 표준점수를 모두 입력해 주세요.');return false}return true}if(active==='workvalue'){const rows=state.workvalue.topValues.filter(x=>x.value||x.score!==''),valid=rows.filter(x=>x.value&&num(x.score)!==null);if(valid.length<3){alert('직업가치 상위 3개 이상의 가치명과 점수를 입력해 주세요.');return false}if(new Set(valid.map(x=>x.value)).size!==valid.length){alert('같은 직업가치를 중복 선택할 수 없습니다.');return false}return true}const keys=READINESS.flatMap(x=>x[1].map(y=>y[0])),miss=keys.filter(k=>num(state.careerreadiness.scores[k])===null);if(miss.length){alert(`진로준비도 T점수가 ${miss.length}개 남았습니다.`);return false}return true}
 function close(){const s=document.getElementById('work24V4');if(s)s.classList.add('work24V4Hidden');setApp(true)}
 window.openWork24AssessmentV4=function(id,opts={}){if(!['riasec','workvalue','careerreadiness'].includes(id))return;active=id;backStep=opts.back??null;nextStep=opts.next??null;setApp(false);const old=document.getElementById('work24AssessmentV3');if(old)old.classList.add('work24AssessmentHidden');render()};
 window.updateWork24V4Score=function(id,k,v){state=read();state[id].scores[k]=String(v).trim()===''?'':Number(v);state[id].status='draft';save();if(id==='riasec')render()};
 window.updateWork24V4Value=function(i,k,v){state=read();while(state.workvalue.topValues.length<5)state.workvalue.topValues.push({value:'',score:''});state.workvalue.topValues[i][k]=k==='score'?(String(v).trim()===''?'':Number(v)):v;state.workvalue.status='draft';save();if(k==='value')render()};
 window.backWork24V4=function(){close();if(backStep!==null&&typeof window.goCareerFlowV4==='function')window.goCareerFlowV4(backStep)};
 window.skipWork24V4=function(){close();if(nextStep!==null&&typeof window.goCareerFlowV4==='function')window.goCareerFlowV4(nextStep)};
 window.saveAndNextWork24V4=function(){state=read();if(!validate())return;state[active].status='complete';state[active].completedAt=new Date().toISOString();if(active==='workvalue')state.workvalue.topValues=state.workvalue.topValues.filter(x=>x.value&&num(x.score)!==null).slice(0,5);save();render();setTimeout(()=>{close();if(nextStep!==null&&typeof window.goCareerFlowV4==='function')window.goCareerFlowV4(nextStep)},60)};
 window.getWork24AssessmentResultsV4=()=>JSON.parse(JSON.stringify(read()));
 window.getWork24AssessmentResultsV3=window.getWork24AssessmentResultsV4;
 window.WORK24_V4={url:URL,values:[...VALUES]};
 function install(){ensureStyle();ensure()}
 if(document.readyState==='complete')install();else window.addEventListener('load',install,{once:true});
})();