const SESSION_KEY='jobfit:instructor:supabase-session';
const config=()=>globalThis.JOBFIT_RESEARCH_CONFIG||{};

export function instructorBackendStatus(){const c=config(),endpointOk=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(c.supabaseUrl||'')&&String(c.publishableKey||'').startsWith('sb_publishable_');return {enabled:c.instructorAuthEnabled===true&&endpointOk,endpointOk,supabaseUrl:c.supabaseUrl||'',publishableKey:c.publishableKey||''}}

export function captureAuthCallback(){const params=new URLSearchParams(location.hash.replace(/^#/,'')),accessToken=params.get('access_token');if(!accessToken)return getSession();const expiresIn=Number(params.get('expires_in')||3600),session={accessToken,refreshToken:params.get('refresh_token')||'',expiresAt:Date.now()+Math.max(60,expiresIn-30)*1000};sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));history.replaceState(null,'',location.pathname+location.search);return session}

export function getSession(){try{const session=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(!session?.accessToken||Number(session.expiresAt)<=Date.now()){sessionStorage.removeItem(SESSION_KEY);return null}return session}catch{return null}}

export async function requestMagicLink(email){const c=instructorBackendStatus();if(!c.enabled)throw new Error('교수자 중앙 DB 로그인이 아직 활성화되지 않았습니다.');const clean=String(email||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean))throw new Error('이메일 주소를 확인해 주세요.');const response=await fetch(`${c.supabaseUrl}/auth/v1/otp`,{method:'POST',headers:{'apikey':c.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:clean,create_user:false,email_redirect_to:new URL('./',location.href).href})});const text=await response.text();if(!response.ok)throw new Error(`로그인 링크 요청 실패 (${response.status}) ${text}`.trim());return {ok:true}}

export async function loadCentralResearch(cohortCode='INJE2026'){const c=instructorBackendStatus(),session=getSession();if(!c.enabled)throw new Error('교수자 중앙 DB 조회가 아직 활성화되지 않았습니다.');if(!session)throw new Error('교수자 로그인이 필요합니다.');const response=await fetch(`${c.supabaseUrl}/rest/v1/rpc/get_research_dashboard`,{method:'POST',headers:{'apikey':c.publishableKey,'Authorization':`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({p_cohort_code:cohortCode})});const text=await response.text();if(response.status===401){sessionStorage.removeItem(SESSION_KEY);throw new Error('로그인 시간이 만료되었습니다. 다시 로그인해 주세요.')}if(!response.ok)throw new Error(`중앙 데이터 조회 실패 (${response.status}) ${text}`.trim());const rows=text?JSON.parse(text):[];return rows.map(row=>row.research_record||row)}

export async function signOutInstructor(){const c=instructorBackendStatus(),session=getSession();sessionStorage.removeItem(SESSION_KEY);if(c.enabled&&session?.accessToken){await fetch(`${c.supabaseUrl}/auth/v1/logout`,{method:'POST',headers:{'apikey':c.publishableKey,'Authorization':`Bearer ${session.accessToken}`}}).catch(()=>{})}}
