import {area,target,copy,prompt,EXAMPLES} from './applicationShared.js?v=1';
export async function render(ctx){
 const s=ctx.getState(),data=structuredClone(s.artifacts?.applicationDocuments||{}),experiences=s.assessments?.experienceCompetency?.experiences||[],p=target(s),e=ctx.escapeHtml;
 const fields={company:'지원 기업',job:'지원 직무',posting:'공고·공식 직무정보·출처',format:'기업 양식·작성 지침',facts:'학력·교육·자격·어학·근무 이력 (보유/준비 중 구분)',experience:'역할·행동·판단 이유·결과·확인 자료',connection:'경험과 직무 연결 검토 결과',resume:'이력서 초안',experienceDoc:'경험기술서 초안',careerDoc:'경력기술서 초안',review:'검토 결과·확인사항',finalResume:'이력서 최종본',finalExperience:'경험기술서 최종본',finalCareer:'경력기술서 최종본'};
 data.company??=p.company||'';data.job??=p.jobTitle||'';data.posting??=p.rawPosting||JSON.stringify(p.requirements||[]);
 document.getElementById('stepRoot').innerHTML=`<section class="card"><div class="kicker">STEP 8</div><h2>이력서·경험기술서·경력기술서</h2><p>실제로 한 일을 지원서에 옮겨봅시다. 기술서는 필요한 경우 선택하세요.</p><div class="block"><h3>01. 지원 대상·내 정보</h3>${['company','job','posting','format','facts'].map(k=>area(ctx,k,fields[k],data[k]||'')).join('')}</div><div class="block"><h3>02. 경험과 직무 연결</h3><label for="experienceSelect">기존 경험 선택</label><select id="experienceSelect"><option value="">선택</option>${experiences.map(x=>`<option value="${e(x.id)}" ${x.id===data.experienceId?'selected':''}>${e(x.title||x.id)}</option>`).join('')}</select><button class="btn secondary" id="loadExperience">선택한 경험 불러오기</button><p>불러오기는 이 화면의 경험 원문을 교체합니다. 기존 초안·최종본은 유지됩니다.</p>${area(ctx,'experience',fields.experience,data.experience||'')}<details><summary>전공·직무별 예시 보기 (가상 자료)</summary>${Object.entries(EXAMPLES).map(([k,v])=>`<p><b>${e(k)}</b> ${e(v)}</p>`).join('')}</details><button class="btn secondary" data-task="connect">직무 연결 프롬프트 복사</button>${area(ctx,'connection',fields.connection,data.connection||'')}</div><div class="block"><h3>03. 이력서 작성</h3><p>담당 역할·수행 내용을 짧게 적고, 확인된 결과만 넣으세요.</p>${area(ctx,'resume',fields.resume,data.resume||'')}<button class="btn secondary" data-task="resume">작성 프롬프트 복사</button><button class="btn secondary" data-review="resume">검토 프롬프트 복사</button>${area(ctx,'finalResume',fields.finalResume,data.finalResume||'')}</div>${[['experienceDoc','04. 경험기술서','프로젝트·실습·동아리 등: 목적·역할·수행 방법·결과물'],['careerDoc','05. 경력기술서','실제 근무 이력: 기관·기간·직책·담당업무·범위·성과']].map(([k,title,help])=>`<div class="block"><h3>${title} · 선택</h3><label><input type="checkbox" id="${k}Enabled" ${data[k+'Enabled']?'checked':''}> 작성하기</label><div id="${k}Panel" ${data[k+'Enabled']?'':'hidden'}><p>${help}</p>${area(ctx,k,fields[k],data[k]||'')}<button class="btn secondary" data-task="${k}">작성 프롬프트 복사</button><button class="btn secondary" data-review="${k}">검토 프롬프트 복사</button>${area(ctx,k==='experienceDoc'?'finalExperience':'finalCareer','최종본',data[k==='experienceDoc'?'finalExperience':'finalCareer']||'')}</div></div>`).join('')}<div class="block"><h3>06. 검토·저장</h3>${area(ctx,'review',fields.review,data.review||'')}<textarea id="promptPreview" hidden readonly aria-label="직접 복사할 프롬프트"></textarea><button class="btn primary" id="saveDocuments">저장</button><button class="btn secondary" id="copyFinal">최종본 복사</button><button class="btn primary" id="nextStep">자기소개서로 이동 →</button><p>입력은 이 브라우저에 자동 저장됩니다. 상단의 내 학습 백업도 보관하세요.</p></div></section>`;
 function save(){for(const k of Object.keys(fields))data[k]=document.getElementById(k).value;for(const k of ['experienceDoc','careerDoc'])data[k+'Enabled']=document.getElementById(k+'Enabled').checked;data.experienceId=document.getElementById('experienceSelect').value;ctx.saveState({artifacts:{applicationDocuments:data}})}
 document.getElementById('stepRoot').oninput=save;
 document.getElementById('loadExperience').onclick=()=>{const x=experiences.find(x=>x.id===document.getElementById('experienceSelect').value);if(!x)return ctx.toast('경험을 선택하세요.');document.getElementById('experience').value=JSON.stringify(x,null,2);save();ctx.toast('경험을 불러왔습니다. 기존 문서와 검토 결과를 다시 확인하세요.');};
 for(const k of ['experienceDoc','careerDoc'])document.getElementById(k+'Enabled').onchange=()=>{document.getElementById(k+'Panel').hidden=!document.getElementById(k+'Enabled').checked;save();};
 const tasks={connect:'실제 행동과 공고 업무를 직접 연결/전이 가능/근거 부족으로 구분하고 이유를 표로 제시. 사실을 유지한 짧은 이력서 표현과 과장되는 표현 제시.',resume:'기업 양식에 맞춰 학력·교육·자격·경험의 이력서 초안 작성.',experienceDoc:'경험명·기간 / 목적·역할 / 수행 방법 / 확인된 결과물 / 직무 연결로 경험기술서 작성. 활동을 근무경력으로 표현하지 않는다.',careerDoc:'기관·부서·직책·기간 / 담당업무 / 업무 범위·수행 방법·확인된 성과로 경력기술서 작성. 경력 인정 여부를 단정하지 않는다.'};
 document.querySelectorAll('[data-task],[data-review]').forEach(b=>b.onclick=()=>{save();const k=b.dataset.task||b.dataset.review;copy(prompt(b.dataset.review?'review':'write',tasks[k],{company:data.company,job:data.job,posting:data.posting,format:data.format,facts:data.facts,experience:data.experience,connection:data.connection,draft:b.dataset.review?data[k]:undefined}),ctx);});
 document.getElementById('saveDocuments').onclick=()=>{save();ctx.toast('저장했습니다.');};document.getElementById('copyFinal').onclick=()=>{save();copy([data.finalResume,data.experienceDocEnabled?data.finalExperience:'',data.careerDocEnabled?data.finalCareer:''].filter(Boolean).join('\n\n'),ctx);};document.getElementById('nextStep').onclick=()=>{save();ctx.navigate(10);};
}
