const JOB_FAMILIES=['기획·전략','인사·조직','재무·회계','영업·사업개발','마케팅·브랜드','고객·서비스','구매·물류·SCM','생산·공정·설비','품질·안전·환경','R&D·연구','IT·데이터','디자인·콘텐츠','공공·행정','상담·교육','기타'];

export async function render(ctx){
  const s=ctx.getState();
  const dna=s.assessments?.careerDNA||{};
  const exp=s.assessments?.experienceCompetency||{experiences:[]};
  const saved=s.artifacts?.jobExplorer||{candidates:[],targets:[],notes:''};
  const data=structuredClone(saved);data.candidates=data.candidates||[];data.targets=data.targets||[];
  const root=document.getElementById('stepRoot');

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 3</div><h2>Job Explorer</h2><p>검사결과를 직무로 자동변환하지 않고, 서로 다른 업무군을 넓게 탐색한 뒤 학생이 직접 Target Job을 선택합니다.</p></div><span class="badge">6주차 · 탐색</span></div>
    <div class="progress"><span style="width:29%"></span></div>
    <div class="callout info"><b>Anti-Collapse Rule</b><br>특정 검사유형 때문에 모든 학생에게 HR·HRD·상담처럼 비슷한 직무가 반복되는 방식을 사용하지 않습니다. <b>흥미 + 가치 + 실제 행동 Evidence + 학생 선택 + 공식 직무정보</b>를 분리해서 확인합니다.</div>

    <div class="block"><h3>1. 나의 탐색 근거 확인</h3><p class="help">직무 후보를 만들 때 최소 3종류의 근거를 따로 봅니다. 서로 다른 근거가 같은 방향을 가리키는지 확인하는 단계입니다.</p><div class="grid3"><div class="miniCard"><b>흥미</b><span>${esc(summaryRIASEC(dna),ctx)}</span></div><div class="miniCard"><b>가치</b><span>${esc(summaryValues(dna),ctx)}</span></div><div class="miniCard"><b>행동 Evidence</b><span>${esc(summaryCompetencies(exp),ctx)}</span></div></div><div class="callout warn"><b>고용24 추천직업은 자동 반영하지 않습니다.</b> STEP 1에 참고용으로 기록했더라도 아래 후보 Pool에는 학생이 공식자료를 확인한 뒤 직접 추가해야 합니다.</div></div>

    <div class="hr"></div><div class="block"><h3>2. AI 직무탐색 프롬프트</h3><p class="help">AI에게 ‘나에게 맞는 직무 3개’를 묻지 않습니다. 서로 다른 업무군을 넓게 만들고, 왜 후보인지와 무엇을 더 검증해야 하는지를 묻습니다.</p><textarea id="jobPrompt" rows="15">${esc(buildPrompt(s),ctx)}</textarea><div class="actions"><button class="btn secondary" id="copyPrompt">프롬프트 복사</button></div></div>

    <div class="hr"></div><div class="block"><h3>3. 직무 후보 Pool</h3><p class="help">권장: 8~12개 후보, 최소 4개 이상의 서로 다른 직무군. 같은 직무군만 이름을 바꿔 반복하지 않습니다.</p>
      <div class="grid2">${txt('jobTitle','직무명','','예: 공정기술, 구매, 데이터분석')}${sel('jobFamily','직무군','',JOB_FAMILIES)}${txt('source','확인 출처','','예: NCS, 고용24 직업정보, 기업 직무소개')}${txt('sourceUrl','출처 URL','','https://...')}</div>
      <div class="grid2" style="margin-top:12px">${area('tasks','대표 업무','','이 직무에서 실제 수행하는 대표 Task 2~3개')}${area('why','관심 근거','','왜 이 직무가 궁금한가?')}${area('evidence','나의 Evidence','','내 경험의 어떤 행동과 연결되는가?')}${area('gap','확인·보완 필요','','아직 모르는 점 또는 부족한 경험은?')}</div>
      <div class="grid4" style="margin-top:12px">${score('interestScore','업무 관심')}${score('evidenceScore','행동근거')}${score('valueScore','가치 적합')}${score('infoScore','정보 확인도')}</div>
      <label class="checkRow"><input type="checkbox" id="sourceVerified"><div><b>공식/실제 자료 확인</b><span>NCS·고용24 직업정보·기업 공식 직무소개·실제 채용공고 중 하나 이상을 직접 확인했습니다.</span></div></label>
      <div class="actions"><button class="btn primary" id="addCandidate">후보 추가</button></div><div class="status" id="status"></div>
    </div>

    <div class="block"><div id="diversityCheck"></div><div id="candidateList"></div></div>
    <div class="hr"></div><div class="block"><h3>4. Target Job 1·2·3 직접 선택</h3><p class="help">표시되는 탐색우선점수는 학생이 직접 매긴 4개 판단값의 단순 평균입니다. 심리검사 적합도나 취업성공확률이 아닙니다.</p><div id="targetPick"></div><div id="targetWarning"></div><div class="field" style="margin-top:12px"><label>선택 메모</label><textarea id="notes" placeholder="왜 이 직무들을 더 깊게 확인하려 하는지, 어떤 근거가 강하고 무엇을 더 확인할지 적으세요.">${esc(data.notes||'',ctx)}</textarea></div><div class="actions"><button class="btn primary" id="saveTargets">Target Job 저장</button><button class="btn secondary" id="nextStep">STEP 4 Job Deep Dive →</button></div></div>
  </section>`;

  renderCandidates();renderTargets();renderDiversity();
  document.getElementById('copyPrompt').addEventListener('click',()=>copy(document.getElementById('jobPrompt').value,ctx));document.getElementById('addCandidate').addEventListener('click',addCandidate);document.getElementById('saveTargets').addEventListener('click',saveTargets);document.getElementById('nextStep').addEventListener('click',()=>{saveTargets();ctx.navigate(4)});

  function addCandidate(){const title=v('jobTitle');const family=v('jobFamily');if(!title){status('직무명을 입력하세요.');return}if(!family){status('직무군을 선택하세요.');return}data.candidates.push({id:`job_${Date.now()}`,title,family,source:v('source'),sourceUrl:v('sourceUrl'),tasks:v('tasks'),why:v('why'),evidence:v('evidence'),gap:v('gap'),interestScore:n('interestScore'),evidenceScore:n('evidenceScore'),valueScore:n('valueScore'),infoScore:n('infoScore'),sourceVerified:!!document.getElementById('sourceVerified').checked,createdAt:new Date().toISOString()});['jobTitle','source','sourceUrl','tasks','why','evidence','gap'].forEach(id=>document.getElementById(id).value='');document.getElementById('jobFamily').value='';['interestScore','evidenceScore','valueScore','infoScore'].forEach(id=>document.getElementById(id).value='3');document.getElementById('sourceVerified').checked=false;persist();renderCandidates();renderTargets();renderDiversity();status('직무 후보를 추가했습니다.');}
  function renderCandidates(){const box=document.getElementById('candidateList');if(!data.candidates.length){box.innerHTML='<div class="placeholder"><b>아직 직무 후보가 없습니다.</b>AI로 넓게 탐색하고 공식자료를 확인한 뒤 후보를 직접 추가하세요.</div>';return}box.innerHTML=data.candidates.map((j,i)=>{const avg=avgScore(j);return `<div class="listCard"><div class="listHead"><div><span class="rankTag">후보 ${i+1}</span><h3>${esc(j.title,ctx)}</h3><div class="muted small">${esc(j.family||'직무군 미입력',ctx)}</div></div><div class="scoreChip">탐색우선 ${avg.toFixed(1)}/5</div></div><div class="grid2"><div><b>대표 Task</b><p>${esc(j.tasks||'—',ctx)}</p></div><div><b>관심 근거</b><p>${esc(j.why||'—',ctx)}</p></div><div><b>행동 Evidence</b><p>${esc(j.evidence||'—',ctx)}</p></div><div><b>확인·보완 필요</b><p>${esc(j.gap||'—',ctx)}</p></div></div><div class="sourceLine"><b>확인 출처</b> ${esc(j.source||'미입력',ctx)} ${j.sourceUrl?`· <a href="${esc(j.sourceUrl,ctx)}" target="_blank" rel="noopener">열기</a>`:''}</div><div class="pillRow"><span class="pill">업무관심 ${j.interestScore||0}</span><span class="pill">행동근거 ${j.evidenceScore||0}</span><span class="pill">가치 ${j.valueScore||0}</span><span class="pill">정보확인 ${j.infoScore||0}</span><span class="pill">${j.sourceVerified?'자료 확인완료':'자료 확인필요'}</span></div><div class="actions"><button class="btn danger smallBtn" data-del="${j.id}">삭제</button></div></div>`}).join('');box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.candidates=data.candidates.filter(x=>x.id!==b.dataset.del);data.targets=data.targets.filter(x=>x!==b.dataset.del);persist();renderCandidates();renderTargets();renderDiversity();}));}
  function renderDiversity(){const box=document.getElementById('diversityCheck');const families=familyStats(data.candidates);if(!data.candidates.length){box.innerHTML='';return}const distinct=Object.keys(families).length;const max=Math.max(...Object.values(families));const total=data.candidates.length;let cls='good',msg=`현재 ${total}개 후보 · ${distinct}개 직무군. 탐색 폭이 적절합니다.`;if(total>=6&&distinct<4){cls='warn';msg=`후보는 ${total}개지만 직무군이 ${distinct}개뿐입니다. 서로 다른 업무군을 더 탐색하세요.`}else if(max>2&&total>=6){cls='warn';const top=Object.entries(families).sort((a,b)=>b[1]-a[1])[0];msg=`${top[0]} 직무군이 ${top[1]}개로 몰려 있습니다. 같은 계열 이름만 바꾼 추천이 반복되지 않았는지 확인하세요.`}box.innerHTML=`<div class="callout ${cls}"><b>직무 후보 다양성 체크</b><br>${esc(msg,ctx)}<div class="pillRow" style="margin-top:8px">${Object.entries(families).map(([k,v])=>`<span class="pill">${esc(k,ctx)} ${v}</span>`).join('')}</div></div>`}
  function renderTargets(){const box=document.getElementById('targetPick');if(!data.candidates.length){box.innerHTML='<div class="callout warn">먼저 직무 후보를 추가하세요.</div>';return}box.innerHTML=data.candidates.map(j=>`<label class="checkRow"><input type="checkbox" data-target="${j.id}" ${data.targets.includes(j.id)?'checked':''}><div><b>${esc(j.title,ctx)}</b><span>${esc(j.family||'',ctx)} · ${j.sourceVerified?'자료 확인완료':'자료 확인필요'}</span></div></label>`).join('');box.querySelectorAll('[data-target]').forEach(c=>c.addEventListener('change',()=>{const ids=[...box.querySelectorAll('[data-target]:checked')];if(ids.length>3){c.checked=false;ctx.toast('Target Job은 최대 3개입니다.')}renderTargetWarning();}));renderTargetWarning();}
  function renderTargetWarning(){const el=document.getElementById('targetWarning');if(!el)return;const ids=[...document.querySelectorAll('[data-target]:checked')].map(x=>x.dataset.target),jobs=ids.map(id=>data.candidates.find(x=>x.id===id)).filter(Boolean);if(!jobs.length){el.innerHTML='';return}const unver=jobs.filter(x=>!x.sourceVerified).length;const fams=new Set(jobs.map(x=>x.family));let msg='';if(unver)msg+=`선택 직무 중 ${unver}개는 공식/실제 자료 확인이 필요합니다. `;if(jobs.length===3&&fams.size===1)msg+='3개가 모두 같은 직무군입니다. 의도한 선택인지 한 번 더 확인하세요.';el.innerHTML=msg?`<div class="callout warn">${esc(msg,ctx)}</div>`:''}
  function saveTargets(){data.targets=[...document.querySelectorAll('[data-target]:checked')].map(x=>x.dataset.target);data.notes=v('notes');persist();status(data.targets.length?`Target Job ${data.targets.length}개를 저장했습니다.`:'직무 후보 Pool을 저장했습니다.');}
  function persist(){data.diversity={families:familyStats(data.candidates),updatedAt:new Date().toISOString()};ctx.saveState({artifacts:{jobExplorer:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function n(id){return Number(document.getElementById(id)?.value||0)}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}
function buildPrompt(s){const d=s.assessments?.careerDNA||{},e=s.assessments?.experienceCompetency||{};const safeDNA={interest:{type:d.interest?.type,riasecStandard:d.interest?.riasecStandard},workValues:d.workValues,personalityBig5:d.personalityBig5,viaTop5:d.viaTop5,reflection:d.reflection};const safeExp={experiences:(e.experiences||[]).map(x=>({title:x.title,category:x.category,action:x.action,result:x.result,evidence:x.evidence,evidenceGrade:x.evidenceGrade,competencyEvidence:x.competencyEvidence}))};return `너는 대학생의 직무 탐색을 돕는 커리어 리서처다. 목표는 '정답 직무'를 맞히는 것이 아니라 서로 다른 업무 후보를 충분히 넓힌 뒤 내가 검증하도록 돕는 것이다.\n\n[Career DNA - 참고근거]\n${json(safeDNA)}\n\n[실제 행동 Evidence - 우선근거]\n${json(safeExp)}\n\n규칙:\n1. 직무 후보를 10개 제안한다. 최소 5개의 서로 다른 직무군을 포함하고, 같은 직무군은 원칙적으로 최대 2개까지만 제안한다.\n2. 직무군 예: 기획·전략 / 인사·조직 / 재무·회계 / 영업·사업개발 / 마케팅·브랜드 / 고객·서비스 / 구매·물류·SCM / 생산·공정·설비 / 품질·안전·환경 / R&D·연구 / IT·데이터 / 디자인·콘텐츠 / 공공·행정 / 상담·교육.\n3. 검사유형(RIASEC, VIA, 성격) 하나만으로 직무를 매칭하지 않는다. 실제 경험에서 확인된 행동 Evidence를 우선한다.\n4. 고용24 결과표의 추천직업은 입력되어 있더라도 우선순위 근거로 사용하지 않는다.\n5. 각 후보마다 ① 직무군 ② 대표 Task 3개 ③ 관심/가치 연결근거 ④ 내 행동 Evidence 연결근거 ⑤ 근거가 약한 점 ⑥ 확인할 공식자료를 표로 정리한다.\n6. Evidence가 없는 후보도 탐색가치가 있으면 포함할 수 있지만 반드시 '새로운 탐색 후보'라고 표시한다.\n7. HR·HRD·상담 등 비슷한 직무가 이름만 바뀌어 반복되지 않았는지 마지막에 스스로 점검한다.\n8. 확인하지 못한 기업·직무 사실은 지어내지 않는다.\n9. 최종 TOP3는 대신 결정하지 않는다. 내가 비교할 질문만 제시한다.`}
function summaryRIASEC(d){const r=d.interest?.riasecStandard||d.interest?.riasecRaw||{};const arr=Object.entries(r).filter(([,v])=>Number.isFinite(v)).sort((a,b)=>b[1]-a[1]).slice(0,3);return arr.length?`${d.interest?.type||''}형(개정) · `+arr.map(([k,v])=>`${k} ${v}`).join(' · '):'STEP 1 RIASEC 결과를 입력하세요.'}
function summaryValues(d){const arr=Object.entries(d.workValues||{}).filter(([,v])=>Number.isFinite(v)).sort((a,b)=>b[1]-a[1]).slice(0,3);return arr.length?arr.map(([k,v])=>`${k} ${v}`).join(' · '):'STEP 1 직업가치관 결과를 입력하세요.'}
function summaryCompetencies(e){const all=[];(e.experiences||[]).forEach(x=>(x.competencyEvidence||[]).forEach(c=>{if(c.keyword&&c.evidence)all.push(`${c.keyword}: ${c.evidence}`)}));if(all.length)return all.slice(0,5).join(' / ');const keys=[];(e.experiences||[]).forEach(x=>(x.competencies||[]).forEach(c=>keys.push(c)));return [...new Set(keys)].slice(0,8).join(', ')||'STEP 2에서 행동근거가 있는 경험을 입력하세요.'}
function familyStats(items){const o={};for(const x of items||[]){const k=x.family||'미분류';o[k]=(o[k]||0)+1}return o}function avgScore(j){return ((+j.interestScore||0)+(+j.evidenceScore||0)+(+j.valueScore||0)+(+j.infoScore||0))/4}function json(v){try{return JSON.stringify(v,null,2)}catch{return String(v)}}function txt(id,label,value,ph){return `<div class="field"><label>${label}</label><input class="input" id="${id}" value="${value||''}" placeholder="${ph||''}"></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function sel(id,label,value,opts){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${opts.map(o=>`<option value="${o}" ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`}function score(id,label){return `<div class="field"><label>${label} <span class="muted">1–5</span></label><select id="${id}"><option value="1">1 낮음</option><option value="2">2</option><option value="3" selected>3 보통</option><option value="4">4</option><option value="5">5 높음</option></select></div>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('프롬프트를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
