const EVIDENCE_LEVELS=['A · 직접 증거','B · 관련 증거','C · 간접 증거','없음'];

export async function render(ctx){
  const s=ctx.getState(),experiences=s.assessments?.experienceCompetency?.experiences||[],jd=s.artifacts?.jdAnalyzer||{postings:[],selectedId:''},posting=jd.postings?.find(x=>x.id===jd.selectedId)||jd.postings?.[0],saved=s.artifacts?.careerAssets||{assets:[]},data=structuredClone(saved),root=document.getElementById('stepRoot');
  data.assets=data.assets||[];

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 8</div><h2>Career Asset Match</h2><p>JD Requirement마다 내 경험의 실제 Evidence를 연결하고, 핵심 GAP를 숨기지 않고 확인합니다.</p></div><span class="badge">9주차</span></div>
    <div class="progress"><span style="width:64%"></span></div>
    ${posting?`<div class="callout info"><b>Target JD</b><br>${esc(posting.company,ctx)} · ${esc(posting.jobTitle,ctx)} · Requirement ${(posting.requirements||[]).length}개</div>`:`<div class="callout warn"><b>Target JD가 없습니다.</b><br>STEP 7에서 실제 채용공고를 먼저 등록하세요.</div>`}
    ${posting?applicationGateHtml(posting,ctx):''}

    <div class="block"><h3>1. Requirement Coverage</h3><p class="help">전체 개수보다 <b>업무핵심·필수 Requirement에 어떤 Evidence가 있는지</b>를 먼저 봅니다.</p><div id="coverageDashboard"></div><div id="criticalGap" style="margin-top:12px"></div><div id="coverageMatrix" style="margin-top:12px"></div></div>

    <div class="hr"></div><div class="block"><h3>2. Experience × Requirement 연결</h3><p class="help">역량명이 비슷하다는 이유만으로 연결하지 않습니다. 실제 행동과 사실 Evidence가 있어야 합니다.</p>
      <div class="grid2">${selectExperience('experienceId','내 경험',experiences)}${selectReq('requirementId','JD Requirement',posting?.requirements||[])}</div>
      <div id="selectedContext" class="callout info">경험과 Requirement를 선택하면 기존 Evidence를 확인합니다.</div>
      <div class="grid2" style="margin-top:12px">${area('proof','증명할 핵심행동','','내가 직접 한 행동을 구체적인 동사로 작성')}${area('fact','사실 Evidence','','수치·피드백·산출물·기록 등 사실로 확인되는 근거')}${area('jobLink','직무 연결 논리','','왜 이 행동이 이 Requirement를 증명하는가?')}${area('gap','남는 GAP','','이 경험으로도 충분히 증명되지 않는 부분')}</div>
      <div class="grid3" style="margin-top:12px">${sel('evidenceLevel','Evidence 수준','',EVIDENCE_LEVELS)}${sel('useFor','우선 활용처','',['이력서','경험기술서','자기소개서','면접','여러 곳'])}${sel('factCheck','사실검증','',['검증완료','추가확인 필요'])}</div>
      <div class="actions"><button class="btn primary" id="addAsset">Career Asset 추가</button><button class="btn secondary" id="copyPrompt">Evidence 검증 프롬프트 복사</button></div><div class="status" id="status"></div>
    </div>

    <div class="block"><div id="assetList"></div></div><div class="actions"><button class="btn primary" id="saveAssets">Career Asset DB 저장</button><button class="btn secondary" id="nextStep">STEP 9 Resume Lab →</button></div>
  </section>`;

  renderAll();['experienceId','requirementId'].forEach(id=>document.getElementById(id).addEventListener('change',renderSelectedContext));document.getElementById('addAsset').addEventListener('click',addAsset);document.getElementById('copyPrompt').addEventListener('click',()=>copy(buildPrompt(),ctx));document.getElementById('saveAssets').addEventListener('click',()=>{persist();status('Career Asset DB를 저장했습니다.');});document.getElementById('nextStep').addEventListener('click',()=>{persist();ctx.navigate(9)});

  function addAsset(){const experienceId=v('experienceId'),requirementId=v('requirementId');if(!experienceId||!requirementId){status('경험과 JD Requirement를 모두 선택하세요.');return;}const x=experiences.find(e=>e.id===experienceId),r=(posting?.requirements||[]).find(r=>r.id===requirementId),level=v('evidenceLevel');if(!level){status('Evidence 수준을 선택하세요.');return;}if(level!=='없음'&&(!v('proof')||!v('fact'))){status('Evidence가 있다면 핵심행동과 사실 Evidence를 입력하세요.');return;}const item={id:`asset_${Date.now()}`,postingId:posting?.id||'',experienceId,experienceTitle:x?.title||'',requirementId,requirement:r?.text||'',requirementType:r?.type||'',requirementLevel:r?.level||'',evidenceQuestion:r?.evidenceQuestion||'',proof:v('proof'),fact:v('fact'),gap:v('gap'),jobLink:v('jobLink'),evidenceLevel:level,strength:legacyStrength(level),useFor:v('useFor'),factCheck:v('factCheck'),sourceExperienceFactChecked:!!x?.factChecked,createdAt:new Date().toISOString()};data.assets.push(item);persist();clear(['proof','fact','gap','jobLink']);renderAll();status(x?.factChecked?'Career Asset을 추가했습니다.':'Career Asset 초안을 추가했습니다. 원경험 Fact Check가 아직 필요합니다.');}
  function renderAll(){renderCoverage();renderCriticalGap();renderAssets();renderSelectedContext();}
  function renderCoverage(){const reqs=posting?.requirements||[],box=document.getElementById('coverageDashboard'),matrix=document.getElementById('coverageMatrix');if(!posting||!reqs.length){box.innerHTML='<div class="callout warn">JD Requirement가 없습니다.</div>';matrix.innerHTML='';return;}const best=reqs.map(r=>({r,level:bestLevel(data.assets.filter(a=>a.requirementId===r.id))})),counts={A:0,B:0,C:0,N:0};best.forEach(x=>{counts[levelKey(x.level)]++});const core=reqs.filter(r=>['업무핵심','필수'].includes(r.level)).length;box.innerHTML=`<div class="grid4"><div class="miniCard"><b>A · 직접증거</b><span>${counts.A}개</span></div><div class="miniCard"><b>B · 관련증거</b><span>${counts.B}개</span></div><div class="miniCard"><b>C · 간접증거</b><span>${counts.C}개</span></div><div class="miniCard"><b>미확보</b><span>${counts.N}개 · 핵심/필수 ${core}개</span></div></div>`;matrix.innerHTML=`<div class="matrixWrap"><table class="matrix"><thead><tr><th>JD Requirement</th><th>중요도</th><th>Evidence 상태</th><th>연결 경험</th><th>다음 행동</th></tr></thead><tbody>${best.map(({r,level})=>{const matches=data.assets.filter(a=>a.requirementId===r.id),names=[...new Set(matches.map(a=>a.experienceTitle).filter(Boolean))];return `<tr><td><b>${esc(r.text,ctx)}</b><br><span class="muted">${esc(r.type||'',ctx)}</span></td><td>${esc(r.level||'—',ctx)}</td><td>${evidenceBadge(level)}</td><td>${esc(names.join(', ')||'없음',ctx)}</td><td>${nextAction(r,level)}</td></tr>`}).join('')}</tbody></table></div>`;}
  function renderCriticalGap(){const box=document.getElementById('criticalGap');if(!box||!posting){return;}const core=(posting.requirements||[]).filter(r=>['업무핵심','필수'].includes(r.level)),weak=core.map(r=>({r,level:bestLevel(data.assets.filter(a=>a.requirementId===r.id))})).filter(x=>x.level==='없음'||x.level.startsWith('C')),gateFail=(posting.gates||[]).filter(g=>g.status==='미충족'),gateCheck=(posting.gates||[]).filter(g=>g.status==='확인 필요');if(gateFail.length){box.innerHTML=`<div class="callout warn"><b>Application Gate 미충족</b><br>${gateFail.map(x=>esc(x.text,ctx)).join(' · ')}<br>Career Asset이 충분해도 지원자격 미충족 문제는 별도로 확인해야 합니다.</div>`;return;}if(gateCheck.length||weak.length){box.innerHTML=`<div class="callout warn"><b>Critical GAP 확인</b><br>${gateCheck.length?`지원자격 확인필요: ${gateCheck.map(x=>esc(x.text,ctx)).join(' · ')}<br>`:''}${weak.length?`핵심/필수 Evidence 보강: ${weak.map(x=>`${esc(x.r.text,ctx)} (${esc(x.level,ctx)})`).join(' · ')}`:''}</div>`;return;}box.innerHTML='<div class="callout good"><b>현재 치명적 GAP 경고 없음</b><br>지원자격과 핵심/필수 Requirement에서 즉시 확인되는 큰 공백은 없습니다. 이는 합격가능성 점수가 아니라 현재 Evidence 점검 결과입니다.</div>';}
  function renderSelectedContext(){const box=document.getElementById('selectedContext');if(!box)return;const x=experiences.find(e=>e.id===v('experienceId')),r=(posting?.requirements||[]).find(q=>q.id===v('requirementId'));if(!x||!r){box.className='callout info';box.innerHTML='경험과 Requirement를 선택하면 기존 Evidence를 확인합니다.';return;}box.className=`callout ${x.factChecked?'good':'warn'}`;box.innerHTML=`<b>${esc(x.title,ctx)} → ${esc(r.text,ctx)}</b><br>Requirement 중요도: ${esc(r.level||'미분류',ctx)} · 경험 Fact Check: ${x.factChecked?'완료':'미완료'}<br>기존 행동: ${esc(x.action||'미입력',ctx)} · 기존 Evidence: ${esc(x.evidence||'미입력',ctx)}${r.evidenceQuestion?`<br><b>JD Evidence 질문</b>: ${esc(r.evidenceQuestion,ctx)}`:''}`;}
  function renderAssets(){const box=document.getElementById('assetList');if(!data.assets.length){box.innerHTML='<div class="placeholder"><b>아직 Career Asset이 없습니다.</b>JD Requirement마다 실제 경험 Evidence를 연결하세요.</div>';return;}box.innerHTML=data.assets.map((a,i)=>`<div class="listCard"><div class="listHead"><div><span class="rankTag">Asset ${i+1}</span><h3>${esc(a.experienceTitle,ctx)}</h3><div class="muted small">→ ${esc(a.requirement,ctx)} · ${esc(a.requirementLevel||'중요도 미분류',ctx)}</div></div><span class="scoreChip">${esc(a.evidenceLevel||legacyLevel(a.strength),ctx)}</span></div><div class="grid2"><div><b>핵심행동</b><p>${esc(a.proof||'—',ctx)}</p></div><div><b>사실 Evidence</b><p>${esc(a.fact||'—',ctx)}</p></div><div><b>직무 연결</b><p>${esc(a.jobLink||'—',ctx)}</p></div><div><b>GAP</b><p>${esc(a.gap||'—',ctx)}</p></div></div><div class="pillRow"><span class="pill">${esc(a.useFor||'활용처 미정',ctx)}</span><span class="pill">${esc(a.factCheck||'검증상태 미정',ctx)}</span>${a.sourceExperienceFactChecked===false?'<span class="pill">원경험 Fact Check 필요</span>':''}</div><div class="actions"><button class="btn danger smallBtn" data-del="${a.id}">삭제</button></div></div>`).join('');box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.assets=data.assets.filter(x=>x.id!==b.dataset.del);persist();renderAll();}));}
  function buildPrompt(){const x=experiences.find(e=>e.id===v('experienceId')),r=(posting?.requirements||[]).find(r=>r.id===v('requirementId'));return `너는 취업 Evidence 검증 면접관이다. 목표는 경험을 그럴듯하게 포장하는 것이 아니라 아래 JD Requirement를 실제로 증명할 수 있는지 판별하는 것이다.\n\n[JD Requirement]\n${JSON.stringify(r||{},null,2)}\n\n[내 경험]\n${JSON.stringify(x||{},null,2)}\n\n규칙:\n1. 역량 키워드가 비슷하다는 이유만으로 연결하지 마라.\n2. 내가 직접 한 행동을 먼저 확인해라.\n3. 결과를 뒷받침하는 수치·피드백·산출물·기록이 있는지 물어라.\n4. 팀 전체의 행동과 내 행동을 분리해라.\n5. 내가 말하지 않은 역할·숫자·성과를 만들지 마라.\n6. Evidence를 A 직접증거 / B 관련증거 / C 간접증거 / 없음 중 하나로 제안하고 이유를 설명해라.\n7. Requirement가 업무핵심/필수인데 Evidence가 C 또는 없음이면 Critical GAP라고 명확히 표시해라.\n8. 부족한 경우 억지 연결 대신 GAP를 명시해라.\n9. 마지막에 지원자료에서 쓸 수 있는 사실문장 2~3개와 면접에서 확인될 꼬리질문을 제시해라.\n\n한 번에 질문 하나씩 시작해라.`}
  function persist(){ctx.saveState({artifacts:{careerAssets:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function clear(ids){ids.forEach(id=>{const el=document.getElementById(id);if(el)el.value=''})}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}

function applicationGateHtml(p,ctx){const fail=(p.gates||[]).filter(x=>x.status==='미충족'),check=(p.gates||[]).filter(x=>x.status==='확인 필요');if(fail.length)return `<div class="callout warn"><b>지원자격 Gate 미충족 ${fail.length}개</b><br>${fail.map(x=>esc(x.text,ctx)).join(' · ')}</div>`;if(check.length||!p.gateReviewed)return `<div class="callout info"><b>지원자격 확인이 아직 끝나지 않았습니다.</b><br>${check.length?check.map(x=>esc(x.text,ctx)).join(' · '):'STEP 7에서 지원자격 원문 대조를 완료하세요.'}</div>`;return '<div class="callout good"><b>Application Gate 검토 완료</b><br>이제 직무 Requirement와 Career Evidence를 분리해 확인합니다.</div>'}
function nextAction(r,level){if(level==='없음')return ['업무핵심','필수'].includes(r.level)?'Critical GAP · 새 경험/학습/프로젝트 계획':'새 경험/학습/프로젝트 GAP 계획';if(level.startsWith('C'))return ['업무핵심','필수'].includes(r.level)?'Critical GAP · 더 직접적인 Evidence 필요':'더 직접적인 Evidence 보강';return '지원자료에서 활용 가능'}
function levelKey(level='없음'){if(level.startsWith('A'))return 'A';if(level.startsWith('B'))return 'B';if(level.startsWith('C'))return 'C';return 'N'}function bestLevel(items=[]){if(!items.length)return '없음';const rank={'A · 직접 증거':4,'B · 관련 증거':3,'C · 간접 증거':2,'없음':1};return [...items].sort((a,b)=>(rank[b.evidenceLevel||legacyLevel(b.strength)]||0)-(rank[a.evidenceLevel||legacyLevel(a.strength)]||0))[0]?.evidenceLevel||legacyLevel(items[0]?.strength)}function legacyStrength(level){return level.startsWith('A')?5:level.startsWith('B')?4:level.startsWith('C')?2:1}function legacyLevel(n){return n>=5?'A · 직접 증거':n>=3?'B · 관련 증거':n>=2?'C · 간접 증거':'없음'}function evidenceBadge(level){return `<span class="pill">${level}</span>`}
function selectExperience(id,label,items){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${items.map(x=>`<option value="${x.id}">${x.title}${x.factChecked?' · ✓':' · 검증필요'}</option>`).join('')}</select></div>`}function selectReq(id,label,items){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${items.map(x=>`<option value="${x.id}">[${x.level||'미분류'}] ${x.text}</option>`).join('')}</select></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function sel(id,label,value,opts){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${opts.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('Evidence 검증 프롬프트를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
