const REQ_TYPES=['Task','Knowledge','Skill','Attitude','Tool','Experience','Qualification','Preferred','기타'];
const LEVELS=['업무핵심','필수','우대','참고'];
const EXPLICIT=['공고에 명시','문맥에서 확인','AI 추론 금지·추가확인'];
const GATE_TYPES=['졸업·학적','전공','경력','자격증','어학','근무지·근무형태','기타'];
const GATE_STATUS=['충족','충족 가능','미충족','확인 필요','해당 없음'];

export async function render(ctx){
  const s=ctx.getState(),saved=s.artifacts?.jdAnalyzer||{postings:[],selectedId:''},data=structuredClone(saved),root=document.getElementById('stepRoot');
  data.postings=data.postings||[];
  const preset=selectedPathway(s);

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 7</div><h2>JD Analyzer</h2><p>실제 채용공고를 지원자격 Gate와 직무 Requirement로 분리해 분석합니다.</p></div><span class="badge">9주차</span></div>
    <div class="progress"><span style="width:57%"></span></div>
    <div class="callout info"><b>두 가지를 섞지 않습니다.</b><br><b>Application Gate</b>는 지원 가능 여부에 영향을 주는 조건이고, <b>Requirement</b>는 경험과 Evidence로 증명해야 하는 업무·KSA·Tool·Experience입니다. 공고에 없는 조건을 AI가 추가하지 않습니다.</div>

    <div class="block"><h3>1. 실제 채용공고 등록</h3><div class="grid4">
      ${txt('company','기업명',preset.company,'예: ○○전자')}${txt('postingTitle','공고명','','예: 2026 하반기 신입채용')}${txt('jobTitle','지원직무',preset.job,'예: 설비기술')}${txt('capturedAt','확인일','',today())}
      ${txt('source','공고 출처','','예: 기업 채용사이트')}${txt('url','공고 URL','','https://...')}${txt('closeDate','마감일','','YYYY-MM-DD')}${txt('postingIdExternal','공고 식별값','','선택: 공고번호/채용ID')}
    </div><div class="field" style="margin-top:12px"><label>채용공고 원문</label><textarea id="rawPosting" rows="14" placeholder="직무내용, 자격요건, 우대사항, 근무지 등 분석할 공고 내용을 붙여넣으세요."></textarea><span class="hint">공개 채용공고 내용만 입력합니다. 지원자의 개인정보나 다른 사람의 서류는 넣지 않습니다.</span></div><div class="actions"><button class="btn primary" id="addPosting">채용공고 저장</button></div><div class="status" id="status"></div></div>

    <div class="block"><div id="postingList"></div></div><div id="detailRoot"></div>
  </section>`;

  renderPostings();renderDetail();document.getElementById('addPosting').addEventListener('click',addPosting);

  function addPosting(){const company=v('company'),jobTitle=v('jobTitle'),url=v('url'),raw=v('rawPosting');if(!company||!jobTitle||!url||!raw){status('기업명·지원직무·공고 URL·공고 원문을 입력하세요.');return;}const p={id:`jd_${Date.now()}`,company,postingTitle:v('postingTitle'),jobTitle,source:v('source'),url,closeDate:v('closeDate'),capturedAt:v('capturedAt'),externalId:v('postingIdExternal'),rawPosting:raw,gates:[],gateReviewed:false,requirements:[],analysisNote:'',unknowns:'',createdAt:new Date().toISOString()};data.postings.push(p);data.selectedId=p.id;persist();clear(['company','postingTitle','jobTitle','source','url','closeDate','postingIdExternal','rawPosting']);renderPostings();renderDetail();status('채용공고를 저장했습니다.');}
  function renderPostings(){const box=document.getElementById('postingList');if(!data.postings.length){box.innerHTML='<div class="placeholder"><b>등록된 채용공고가 없습니다.</b>실제로 지원해볼 공고 하나를 선택해 등록하세요.</div>';return;}box.innerHTML=data.postings.map(p=>{const g=gateSummary(p);return `<div class="listCard"><div class="listHead"><div><span class="rankTag">JD</span><h3>${esc(p.company,ctx)} · ${esc(p.jobTitle,ctx)}</h3><div class="muted small">${esc(p.postingTitle||'',ctx)} · 확인 ${esc(p.capturedAt||'미입력',ctx)} ${p.closeDate?`· 마감 ${esc(p.closeDate,ctx)}`:''}</div></div><div class="actions" style="margin-top:0"><button class="btn ${data.selectedId===p.id?'primary':'outline'} smallBtn" data-select="${p.id}">분석</button><button class="btn danger smallBtn" data-del="${p.id}">삭제</button></div></div><div class="sourceLine"><b>Application Gate</b> ${g.text} · <b>Requirement</b> ${(p.requirements||[]).length}개 ${p.url?`· <a href="${esc(p.url,ctx)}" target="_blank" rel="noopener">공고 원문 ↗</a>`:''}</div></div>`}).join('');box.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>{data.selectedId=b.dataset.select;persist();renderPostings();renderDetail();}));box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.postings=data.postings.filter(x=>x.id!==b.dataset.del);if(data.selectedId===b.dataset.del)data.selectedId=data.postings[0]?.id||'';persist();renderPostings();renderDetail();}));}
  function renderDetail(){const box=document.getElementById('detailRoot'),p=data.postings.find(x=>x.id===data.selectedId);if(!p){box.innerHTML='';return;}p.gates=p.gates||[];p.requirements=p.requirements||[];box.innerHTML=`<div class="hr"></div><div class="block"><div class="sectionHead"><div><h3>2. ${esc(p.company,ctx)} ${esc(p.jobTitle,ctx)} — JD 구조화</h3><p class="help">공고 원문에 있는 사실만 분류합니다.</p></div><span class="badge">${jdCoverageLabel(p)}</span></div><div class="field"><label>AI 분석 프롬프트</label><textarea id="jdPrompt" rows="16">${esc(buildPrompt(p),ctx)}</textarea></div><div class="actions"><button class="btn secondary" id="copyJdPrompt">프롬프트 복사</button></div></div>

    <div class="hr"></div><div class="block"><h3>3. Application Gate · 지원자격 조건</h3><p class="help">졸업시점·전공·경력·필수자격처럼 지원 가능 여부에 직접 영향을 주는 조건만 등록합니다. ‘우대’는 Gate가 아니라 Requirement/Preferred로 분류합니다.</p>
      <div class="grid3">${txt('gateText','지원자격 조건','','예: 2027년 2월 졸업예정자')}${sel('gateType','구분','',GATE_TYPES)}${sel('gateStatus','나의 현재 상태','',GATE_STATUS)}</div>
      <div class="grid2" style="margin-top:12px">${area('gateExcerpt','공고 근거 문구','','공고에서 확인한 근거')}${area('gateAction','필요 조치','','확인·취득·서류준비 등 필요한 다음 행동')}</div><div class="actions"><button class="btn primary" id="addGate">Gate 추가</button></div><div id="gateDashboard" style="margin-top:14px"></div><div id="gateList" style="margin-top:12px"></div>
      <label class="checkRow"><input type="checkbox" id="gateReviewed" ${p.gateReviewed?'checked':''}><div><b>지원자격 확인 완료</b><span>공고의 자격요건·지원대상·필수조건을 원문과 대조했습니다. 별도 Gate가 없다면 ‘해당 없음’임을 확인한 뒤 체크합니다.</span></div></label>
    </div>

    <div class="hr"></div><div class="block"><h3>4. Requirement Evidence Table</h3><p class="help">지원자격을 제외한 실제 업무·KSA·Tool·Experience 요구를 분해합니다.</p><div class="grid4">${txt('reqText','요구사항','','예: 생산설비 데이터 분석 및 개선')}${sel('reqType','구분','',REQ_TYPES)}${sel('reqLevel','중요도','',LEVELS)}${sel('reqExplicit','명시 수준','',EXPLICIT)}</div>
      <div class="grid2" style="margin-top:12px">${area('reqExcerpt','공고 근거 문구','','원문 의미를 훼손하지 않는 짧은 근거 문구/섹션')}${area('reqSignal','역량·행동 신호','','이 요구가 지원자에게 요구하는 실제 행동은 무엇인가?')}${area('reqQuestion','Evidence 질문','','지원자가 이 요구를 증명하려면 어떤 경험질문에 답해야 하는가?')}${area('reqUnknown','추가 확인','','공고만으로 알 수 없어 추가 확인해야 하는 정보')}</div>
      <div class="actions"><button class="btn primary" id="addReq">Requirement 추가</button></div><div id="reqDashboard" style="margin-top:14px"></div><div id="reqList" style="margin-top:14px"></div></div>

    <div class="hr"></div><div class="block"><h3>5. Job Deep Dive와 실제 JD 비교</h3><div id="deepCompare" class="summaryBox">${deepCompareHtml(s,p,ctx)}</div><p class="help" style="margin-top:10px">STEP 4의 일반 직무분석과 실제 공고가 다르면 이번 지원에서는 JD를 우선하되, 공고 하나를 직무 전체의 정의로 일반화하지 않습니다.</p></div>

    <div class="hr"></div><div class="block"><h3>6. JD 핵심해석</h3><div class="grid2">${area('analysisNote','내 해석',p.analysisNote,'이 공고가 실제로 중요하게 보는 것을 근거와 함께 3가지로 요약')}${area('unknowns','아직 모르는 것',p.unknowns,'공고에 없어서 기업자료·추가공고·면접에서 확인해야 할 정보')}</div><div id="gateAlert" class="callout ${gateAlertClass(p)}">${gateAlertText(p)}</div><div class="callout ${jdReady(p)?'good':'warn'}" id="jdCoverage">${jdCoverageText(p)}</div><div class="actions"><button class="btn primary" id="saveJD">JD 분석 저장</button><button class="btn secondary" id="nextStep">STEP 8 Career Asset Match →</button></div><div class="status" id="detailStatus"></div></div>`;
    renderGates(p);renderReqs(p);renderReqDashboard(p);
    document.getElementById('copyJdPrompt').addEventListener('click',()=>copy(document.getElementById('jdPrompt').value,ctx));document.getElementById('addGate').addEventListener('click',()=>addGate(p));document.getElementById('addReq').addEventListener('click',()=>addReq(p));document.getElementById('saveJD').addEventListener('click',()=>saveDetail(p,true));document.getElementById('nextStep').addEventListener('click',()=>{saveDetail(p,false);ctx.navigate(8)});
  }
  function addGate(p){const text=val('gateText'),excerpt=val('gateExcerpt'),statusVal=val('gateStatus');if(!text||!excerpt||!statusVal){ctx.toast('지원자격 조건·공고 근거·현재상태를 입력하세요.');return;}p.gates.push({id:`gate_${Date.now()}`,text,type:val('gateType'),status:statusVal,excerpt,action:val('gateAction')});persist();clear(['gateText','gateExcerpt','gateAction']);renderGates(p);refreshCoverage(p);ctx.toast('Application Gate를 추가했습니다.');}
  function renderGates(p){const dash=document.getElementById('gateDashboard'),box=document.getElementById('gateList');const g=p.gates||[],fail=g.filter(x=>x.status==='미충족').length,check=g.filter(x=>x.status==='확인 필요').length,ok=g.filter(x=>['충족','충족 가능','해당 없음'].includes(x.status)).length;dash.innerHTML=`<div class="grid3"><div class="miniCard"><b>충족/가능</b><span>${ok}개</span></div><div class="miniCard"><b>확인 필요</b><span>${check}개</span></div><div class="miniCard"><b>미충족</b><span>${fail}개</span></div></div>`;if(!g.length){box.innerHTML='<div class="placeholder"><b>등록한 Application Gate가 없습니다.</b>공고에 필수 지원자격이 있는지 먼저 확인하세요.</div>';return;}box.innerHTML=`<div class="matrixWrap"><table class="matrix"><thead><tr><th>지원자격</th><th>구분</th><th>현재상태</th><th>공고근거</th><th>필요조치</th><th></th></tr></thead><tbody>${g.map(x=>`<tr><td><b>${esc(x.text,ctx)}</b></td><td>${esc(x.type||'—',ctx)}</td><td>${esc(x.status,ctx)}</td><td>${esc(x.excerpt,ctx)}</td><td>${esc(x.action||'—',ctx)}</td><td><button class="btn danger smallBtn" data-delgate="${x.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`;box.querySelectorAll('[data-delgate]').forEach(b=>b.addEventListener('click',()=>{p.gates=p.gates.filter(x=>x.id!==b.dataset.delgate);persist();renderGates(p);refreshCoverage(p);}));}
  function addReq(p){const text=val('reqText'),excerpt=val('reqExcerpt');if(!text||!excerpt){ctx.toast('요구사항과 공고 근거 문구를 입력하세요.');return;}p.requirements=p.requirements||[];p.requirements.push({id:`jdr_${Date.now()}`,text,type:val('reqType'),level:val('reqLevel'),explicitness:val('reqExplicit'),excerpt,signal:val('reqSignal'),evidenceQuestion:val('reqQuestion'),unknown:val('reqUnknown')});persist();clear(['reqText','reqExcerpt','reqSignal','reqQuestion','reqUnknown']);renderReqs(p);renderReqDashboard(p);refreshCoverage(p);ctx.toast('Requirement를 추가했습니다.');}
  function renderReqs(p){const box=document.getElementById('reqList');if(!p.requirements?.length){box.innerHTML='<div class="placeholder"><b>Requirement가 아직 없습니다.</b>Task·Skill·Tool·Experience 요구를 원문 근거와 함께 분리하세요.</div>';return;}box.innerHTML=`<div class="matrixWrap"><table class="matrix"><thead><tr><th>Requirement</th><th>유형</th><th>중요도</th><th>명시</th><th>근거</th><th>Evidence 질문</th><th></th></tr></thead><tbody>${p.requirements.map(r=>`<tr><td><b>${esc(r.text,ctx)}</b><br><span class="muted">${esc(r.signal||'',ctx)}</span></td><td>${esc(r.type||'—',ctx)}</td><td>${esc(r.level||'—',ctx)}</td><td>${esc(r.explicitness||'—',ctx)}</td><td>${esc(r.excerpt||r.source||'—',ctx)}</td><td>${esc(r.evidenceQuestion||'—',ctx)}</td><td><button class="btn danger smallBtn" data-delreq="${r.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`;box.querySelectorAll('[data-delreq]').forEach(b=>b.addEventListener('click',()=>{p.requirements=p.requirements.filter(x=>x.id!==b.dataset.delreq);persist();renderReqs(p);renderReqDashboard(p);refreshCoverage(p);}));}
  function renderReqDashboard(p){const box=document.getElementById('reqDashboard');if(!box)return;const req=p.requirements||[],types={};req.forEach(r=>types[r.type||'미분류']=(types[r.type||'미분류']||0)+1);const core=req.filter(r=>['업무핵심','필수'].includes(r.level)).length,questions=req.filter(r=>r.evidenceQuestion).length;box.innerHTML=`<div class="grid3"><div class="miniCard"><b>Requirement</b><span>${req.length}개 · 핵심/필수 ${core}개</span></div><div class="miniCard"><b>유형 분포</b><span>${Object.entries(types).map(([k,v])=>`${k} ${v}`).join(' · ')||'없음'}</span></div><div class="miniCard"><b>Evidence 질문</b><span>${questions}/${req.length||0}개 작성</span></div></div>`;}
  function saveDetail(p,toast){p.analysisNote=val('analysisNote');p.unknowns=val('unknowns');p.gateReviewed=!!document.getElementById('gateReviewed')?.checked;p.updatedAt=new Date().toISOString();persist();refreshCoverage(p);renderPostings();document.getElementById('detailStatus').textContent='JD 분석을 저장했습니다.';if(toast)ctx.toast('JD 분석 저장 완료');}
  function refreshCoverage(p){const el=document.getElementById('jdCoverage');if(el){el.className=`callout ${jdReady(p)?'good':'warn'}`;el.textContent=jdCoverageText(p)}const ga=document.getElementById('gateAlert');if(ga){ga.className=`callout ${gateAlertClass(p)}`;ga.textContent=gateAlertText(p)}}
  function persist(){ctx.saveState({artifacts:{jdAnalyzer:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function val(id){return document.getElementById(id)?.value?.trim()||''}function clear(ids){ids.forEach(id=>{const el=document.getElementById(id);if(el)el.value=''})}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}

function selectedPathway(s){const fit=s.artifacts?.careerFit||{},x=fit.comparisons?.find(a=>a.id===fit.selectedId),e=s.artifacts?.jobExplorer||{},ic=s.artifacts?.industryCompany||{};return {job:e.candidates?.find(j=>j.id===x?.jobId)?.title||'',company:ic.companies?.find(c=>c.id===x?.companyId)?.name||''}}
function gateSummary(p){const g=p.gates||[],fail=g.filter(x=>x.status==='미충족').length,check=g.filter(x=>x.status==='확인 필요').length;if(fail)return {text:`미충족 ${fail}개`};if(check)return {text:`확인필요 ${check}개`};return {text:p.gateReviewed?'검토완료':`${g.length}개 · 검토필요`}}
function gateAlertClass(p){if((p.gates||[]).some(x=>x.status==='미충족'))return 'warn';if(!p.gateReviewed||(p.gates||[]).some(x=>x.status==='확인 필요'))return 'info';return 'good'}
function gateAlertText(p){const fail=(p.gates||[]).filter(x=>x.status==='미충족'),check=(p.gates||[]).filter(x=>x.status==='확인 필요');if(fail.length)return `Application Gate 미충족 ${fail.length}개: ${fail.map(x=>x.text).join(' / ')}. 지원 전 공고의 예외조건·인정기준을 직접 확인하세요.`;if(check.length)return `지원자격 확인 필요 ${check.length}개: ${check.map(x=>x.text).join(' / ')}`;return p.gateReviewed?'지원자격 원문 대조 완료.':'지원자격 확인 완료 체크가 필요합니다.'}
function jdReady(p){const req=p.requirements||[];return !!p.rawPosting&&req.length>=5&&req.some(r=>r.type==='Task')&&req.some(r=>['Skill','Experience','Qualification'].includes(r.type))&&!!p.gateReviewed}
function jdCoverageLabel(p){return jdReady(p)?'JD 근거 기본충족':'JD 근거 보강'}
function jdCoverageText(p){const req=p.requirements||[],withQ=req.filter(r=>r.evidenceQuestion).length;return jdReady(p)?`기본 분석 기준 충족: 지원자격 검토 완료 · Requirement ${req.length}개 · Evidence 질문 ${withQ}개. 이제 각 요구를 내 실제 경험과 매칭하세요.`:`분석 보강 권장: 지원자격 검토 + Requirement ${req.length}/5+ + Task 포함 + Skill/Experience/Qualification 중 최소 1개. 수량보다 공고 원문 근거가 우선입니다.`}
function deepCompareHtml(s,p,ctx){const deep=s.artifacts?.jobDeepDive?.analyses||{},job=Object.values(deep).find(a=>a.jobTitle===p.jobTitle)||Object.values(deep)[0];if(!job)return '<p>STEP 4 Job Deep Dive 결과가 없습니다. 실제 JD 분석은 계속할 수 있지만 일반 직무근거와의 비교가 필요합니다.</p>';const tasks=(job.tasks||[]).map(x=>x.name).filter(Boolean),reqs=(p.requirements||[]).map(x=>x.text);return `<div class="grid2"><div><b>STEP 4에서 확인한 Task</b><p>${tasks.length?tasks.map(x=>esc(x,ctx)).join(' · '):'Task Evidence 미입력'}</p></div><div><b>현재 JD Requirement</b><p>${reqs.length?reqs.slice(0,8).map(x=>esc(x,ctx)).join(' · '):'아직 Requirement 미입력'}</p></div></div>`}
function buildPrompt(p){return `너는 채용공고 분석가다. 아래 실제 공고만 근거로 분석해라. 일반 직무상식·기업정보·가상의 요구사항을 추가하지 마라. 공고에 없으면 '공고에서 확인되지 않음'으로 표시해라.\n\n[기업] ${p.company}\n[직무] ${p.jobTitle}\n[공고명] ${p.postingTitle||''}\n[확인일] ${p.capturedAt||''}\n\n[채용공고 원문]\n${p.rawPosting||'(원문 미입력)'}\n\n먼저 두 종류로 완전히 분리해라.\nA. Application Gate: 졸업/학적, 전공, 필수경력, 필수자격증, 필수어학, 근무조건처럼 지원 가능 여부에 직접 영향을 주는 조건\nB. Job Requirement: Task / Knowledge / Skill / Attitude / Tool / Experience / Qualification / Preferred처럼 경험과 Evidence로 증명할 요소\n\n각 항목에 반드시 공고 근거 문구를 붙여라. '우대'를 필수 Gate로 바꾸지 말고, 공고에 없는 조건을 추가하지 마라.\n\nRequirement는 다음 구조로 정리해라.\n- Requirement 원문 요약\n- Type\n- 중요도: 업무핵심 / 필수 / 우대 / 참고\n- 공고 근거 문구\n- 요구되는 행동·역량 신호\n- 지원자가 답해야 할 Evidence 질문\n- 추가 확인이 필요한 Unknown\n\n마지막에 1) 지원자격 Gate 2) 반복되는 핵심 Requirement 3) 반드시 증명해야 할 Evidence 4) 공고만으로 모르는 정보를 정리해라. 추측은 금지한다.`}
function today(){return new Date().toISOString().slice(0,10)}function txt(id,label,value,ph){return `<div class="field"><label>${label}</label><input class="input" id="${id}" value="${value||''}" placeholder="${ph||''}"></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function sel(id,label,value,opts){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${opts.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('JD 분석 프롬프트를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
