export async function render(ctx){
  const s=ctx.getState(),jd=s.artifacts?.jdAnalyzer||{postings:[],selectedId:''},posting=jd.postings?.find(x=>x.id===jd.selectedId)||jd.postings?.[0],allAssets=s.artifacts?.careerAssets?.assets||[],assets=allAssets.filter(a=>(a.evidenceLevel||legacyLevel(a.strength))!=='없음'),saved=s.artifacts?.coverLetterLab||{questions:[]},data=structuredClone(saved),root=document.getElementById('stepRoot');
  data.questions=data.questions||[];

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 10</div><h2>Cover Letter Lab</h2><p>문항 평가의도 → JD Requirement → Career Asset을 연결한 뒤, 학생의 실제 답변으로 자기소개서를 만듭니다.</p></div><span class="badge">10주차</span></div><div class="progress"><span style="width:79%"></span></div>
    ${posting?`<div class="callout info"><b>Target</b><br>${esc(posting.company,ctx)} · ${esc(posting.jobTitle,ctx)}</div>`:''}
    <div class="block"><h3>0. Cover Letter Readiness</h3><div id="coverDashboard"></div></div>

    <div class="hr"></div><div class="block"><h3>1. 문항 → 평가의도 → JD 연결</h3><div class="grid2">${area('question','자기소개서 문항','','문항 전체를 그대로 입력')}${area('intent','내가 해석한 평가의도','','기업이 이 문항으로 무엇을 확인하려 하는가?')}</div><div class="grid2" style="margin-top:12px">${selectReq('requirementId','관련 JD Requirement',posting?.requirements||[])}${area('claim','이 문항에서 증명할 핵심주장','','예: 데이터를 근거로 문제원인을 구조화하고 개선안을 실행했다')}</div><div id="questionGuard" class="callout info">JD Requirement와 Career Asset을 연결하면 정합성을 확인합니다.</div></div>

    <div class="hr"></div><div class="block"><h3>2. 사용할 Career Asset 선택</h3><p class="help">원칙적으로 문항당 가장 강한 1~2개 Evidence만 사용합니다. 경험을 많이 섞는 것이 좋은 자소서는 아닙니다.</p><div id="assetChecks">${assets.length?assets.map(a=>`<label class="checkRow"><input type="checkbox" data-asset="${a.id}"><div><b>${esc(a.experienceTitle,ctx)}</b><span>${esc(a.requirement,ctx)} · ${esc(a.evidenceLevel||legacyLevel(a.strength),ctx)} · ${esc(a.factCheck||'검증상태 미정',ctx)}</span></div></label>`).join(''):'<div class="callout warn">STEP 8에서 사용 가능한 Career Asset을 먼저 만들어 주세요.</div>'}</div><div id="assetGuard" class="callout info">Career Asset을 선택하면 사실검증·Requirement 연결을 확인합니다.</div><div class="actions"><button class="btn secondary" id="copyPrompt">AI Experience Interview 프롬프트 복사</button></div></div>

    <div class="hr"></div><div class="block"><h3>3. 내 답변에서 초안 만들기</h3><div class="grid2">${area('rawAnswer','내 원래 답변 · Raw Voice','','AI 인터뷰에서 내가 실제로 말하거나 입력한 내용')}${area('structure','구조화 메모','','핵심주장 / 상황 / Action / Reasoning / Result / Evidence / JD 연결')}</div><div class="field" style="margin-top:12px"><label>AI 초안</label><textarea id="draft" rows="10" placeholder="AI가 구조화한 초안. 최종본이 아닙니다."></textarea></div><label class="checkRow"><input type="checkbox" id="factChecked"><div><b>Cover Letter Fact Check</b><span>경험·수치·역할·결과가 선택한 Career Asset 및 Raw Voice와 일치합니다.</span></div></label><div class="actions"><button class="btn primary" id="addQuestion">문항 저장</button></div><div class="status" id="status"></div></div>

    <div class="block"><div id="questionList"></div></div><div class="actions"><button class="btn primary" id="saveAll">Cover Letter Lab 저장</button><button class="btn secondary" id="nextStep">STEP 11 Interview Lab →</button></div>
  </section>`;

  renderAll();document.querySelectorAll('[data-asset]').forEach(x=>x.addEventListener('change',()=>{enforceAssetLimit(x);renderGuards()}));document.getElementById('requirementId').addEventListener('change',renderGuards);document.getElementById('copyPrompt').addEventListener('click',()=>copy(buildPrompt(),ctx));document.getElementById('addQuestion').addEventListener('click',addQuestion);document.getElementById('saveAll').addEventListener('click',()=>{persist();status('자기소개서 작업을 저장했습니다.');});document.getElementById('nextStep').addEventListener('click',()=>{persist();ctx.navigate(11)});

  function renderAll(){renderDashboard();renderQuestions();renderGuards()}
  function selectedAssets(){const ids=[...document.querySelectorAll('[data-asset]:checked')].map(x=>x.dataset.asset);return assets.filter(a=>ids.includes(a.id))}
  function enforceAssetLimit(changed){const checked=[...document.querySelectorAll('[data-asset]:checked')];if(checked.length>2){changed.checked=false;ctx.toast('문항당 Career Asset은 최대 2개를 권장·허용합니다.');}}
  function alignment(){const sel=selectedAssets(),reqId=v('requirementId'),weak=sel.filter(a=>!isAssetVerified(a)),matched=reqId?sel.filter(a=>a.requirementId===reqId):[];return {sel,reqId,weak,matched,aligned:!!reqId&&matched.length>0&&weak.length===0&&sel.length<=2}}
  function renderGuards(){const a=alignment(),assetBox=document.getElementById('assetGuard'),qBox=document.getElementById('questionGuard');if(!a.sel.length){assetBox.className='callout info';assetBox.textContent='Career Asset을 선택하면 사실검증·Requirement 연결을 확인합니다.';}else if(a.weak.length){assetBox.className='callout warn';assetBox.innerHTML=`<b>Fact Check 필요</b><br>${a.weak.map(x=>esc(x.experienceTitle,ctx)).join(', ')}의 Career Asset 또는 원경험 Fact Check가 완료되지 않았습니다.`;}else if(a.reqId&&!a.matched.length){assetBox.className='callout warn';assetBox.innerHTML='<b>Requirement 연결 불일치</b><br>선택한 Career Asset 중 현재 JD Requirement를 직접 연결한 자산이 없습니다. 다른 자산을 선택하거나 연결 논리를 다시 확인하세요.';}else{assetBox.className='callout good';assetBox.innerHTML='<b>선택 Evidence 확인</b><br>선택한 Career Asset의 사실검증 및 JD Requirement 연결이 확인되었습니다.';}if(!a.reqId){qBox.className='callout info';qBox.textContent='관련 JD Requirement를 선택하세요.';}else if(a.matched.length){qBox.className='callout good';qBox.textContent='문항의 핵심주장을 실제 JD Requirement와 Career Asset Evidence에 연결할 수 있습니다.';}else{qBox.className='callout warn';qBox.textContent='선택한 JD Requirement와 연결되는 Career Asset Evidence가 아직 없습니다.';}}
  function renderDashboard(){const box=document.getElementById('coverDashboard'),finals=data.questions.filter(x=>x.status==='final-ready'||(x.factChecked&&x.assetVerified&&x.requirementAligned)).length,drafts=data.questions.length-finals;box.innerHTML=`<div class="grid3"><div class="miniCard"><b>저장 문항</b><span>${data.questions.length}개</span></div><div class="miniCard"><b>Final Ready</b><span>${finals}개</span></div><div class="miniCard"><b>Draft / 검증필요</b><span>${drafts}개</span></div></div>`;}
  function addQuestion(){const q=v('question'),a=alignment();if(!q){status('자기소개서 문항을 입력하세요.');return;}if(!v('intent')){status('내가 해석한 평가의도를 먼저 작성하세요.');return;}if(!a.reqId){status('관련 JD Requirement를 선택하세요.');return;}if(!a.sel.length){status('사용할 Career Asset을 1개 이상 선택하세요.');return;}if(a.sel.length>2){status('Career Asset은 1~2개만 선택하세요.');return;}if(!v('rawAnswer')){status('AI 초안보다 학생의 Raw Voice 또는 인터뷰 답변을 먼저 남기세요.');return;}const r=(posting?.requirements||[]).find(x=>x.id===a.reqId),factChecked=document.getElementById('factChecked').checked,assetVerified=a.weak.length===0,requirementAligned=a.matched.length>0,statusValue=factChecked&&assetVerified&&requirementAligned?'final-ready':'draft';const item={id:`cl_${Date.now()}`,postingId:posting?.id||'',company:posting?.company||'',jobTitle:posting?.jobTitle||'',question:q,intent:v('intent'),requirementId:r?.id||'',requirement:r?.text||'',claim:v('claim'),assetIds:a.sel.map(x=>x.id),rawAnswer:v('rawAnswer'),structure:v('structure'),draft:v('draft'),factChecked,assetVerified,requirementAligned,status:statusValue,createdAt:new Date().toISOString()};data.questions.push(item);persist();clear(['question','intent','claim','rawAnswer','structure','draft']);document.getElementById('requirementId').value='';document.querySelectorAll('[data-asset]').forEach(x=>x.checked=false);document.getElementById('factChecked').checked=false;renderAll();status(statusValue==='final-ready'?'Evidence 연결과 사실검증이 완료된 문항을 저장했습니다.':'Draft로 저장했습니다. Requirement 연결과 Fact Check를 확인하세요.');}
  function renderQuestions(){const box=document.getElementById('questionList');if(!data.questions.length){box.innerHTML='<div class="placeholder"><b>아직 저장한 자소서 문항이 없습니다.</b>문항 → 평가의도 → JD Requirement → Career Asset 순서로 연결하세요.</div>';return;}box.innerHTML=data.questions.map((q,i)=>{const used=(q.assetIds||[]).map(id=>allAssets.find(a=>a.id===id)?.experienceTitle).filter(Boolean),ready=q.status==='final-ready'||(q.factChecked&&q.assetVerified&&q.requirementAligned);return `<div class="listCard"><div class="listHead"><div><span class="rankTag">문항 ${i+1}</span><h3>${esc(q.question,ctx)}</h3><div class="muted small">${esc(q.intent||'평가의도 미작성',ctx)}${q.requirement?` · JD: ${esc(q.requirement,ctx)}`:''}</div></div>${ready?'<span class="scoreChip">Final Ready</span>':'<span class="scoreChip" style="background:#fff8e6;color:#9a6700;border-color:#f3dfaa">Draft · 검증필요</span>'}</div><div class="grid2"><div><b>핵심주장</b><p>${esc(q.claim||'—',ctx)}</p></div><div><b>사용 Evidence</b><p>${esc(used.join(', ')||'—',ctx)}</p></div></div><div><b>AI 초안</b><p>${esc(q.draft||'—',ctx)}</p></div><div class="actions"><button class="btn danger smallBtn" data-del="${q.id}">삭제</button></div></div>`}).join('');box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.questions=data.questions.filter(x=>x.id!==b.dataset.del);persist();renderAll();}));}
  function buildPrompt(){const a=alignment(),r=(posting?.requirements||[]).find(x=>x.id===a.reqId);return `지금부터 자기소개서를 대신 써주는 작가가 아니라 내 경험을 검증하고 꺼내는 취업 인터뷰어가 되어줘.\n\n[기업/직무]\n${posting?`${posting.company} / ${posting.jobTitle}`:'미등록'}\n\n[자기소개서 문항]\n${v('question')||'미입력'}\n\n[내가 해석한 평가의도]\n${v('intent')||'미입력'}\n\n[관련 JD Requirement]\n${JSON.stringify(r||{},null,2)}\n\n[내가 증명하려는 핵심주장]\n${v('claim')||'미입력'}\n\n[선택한 Career Asset]\n${JSON.stringify(a.sel,null,2)}\n\n규칙:\n1. 먼저 문항 평가의도와 선택한 JD Requirement 연결이 타당한지 점검한다.\n2. 선택한 Career Asset 중 해당 Requirement에 직접 연결된 자산이 있는지 확인한다.\n3. Career Asset의 Evidence 수준과 사실검증 상태를 확인한다.\n4. 경험은 최대 1~2개로 제한하고 최종 선택은 나에게 묻는다.\n5. 경험이 정해지면 한 번에 질문 하나씩 하며 내가 직접 한 Action, Reasoning, Result, Evidence를 확인한다.\n6. 내가 말하지 않은 수치·성과·역할은 만들지 않는다.\n7. Evidence가 약하거나 Requirement 연결이 약하면 과장하지 말고 GAP라고 말한다.\n8. 충분한 답변이 모이기 전에는 완성문을 쓰지 않는다.\n9. 마지막에 먼저 '핵심주장 → 상황 → Action → Reasoning → Result/Evidence → JD 연결' 구조를 보여주고 내가 확인하면 초안을 작성한다.\n10. 기업 칭찬·상투어를 자동 추가하지 않는다.\n11. 초안 끝에 Career Asset 원자료와 다시 확인해야 할 표현을 표시한다.\n\n첫 질문부터 시작해줘.`}
  function persist(){ctx.saveState({artifacts:{coverLetterLab:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function clear(ids){ids.forEach(id=>{const el=document.getElementById(id);if(el)el.value=''})}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}
function isAssetVerified(a){return !!a&&a.factCheck==='검증완료'&&a.sourceExperienceFactChecked!==false}
function legacyLevel(n){return n>=5?'A · 직접 증거':n>=3?'B · 관련 증거':n>=2?'C · 간접 증거':'없음'}function selectReq(id,label,items){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${items.map(x=>`<option value="${x.id}">[${x.level||'미분류'}] ${x.text}</option>`).join('')}</select></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('자소서 인터뷰 프롬프트를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
