export async function render(ctx){
  const s=ctx.getState(),jd=s.artifacts?.jdAnalyzer||{postings:[],selectedId:''},posting=jd.postings?.find(x=>x.id===jd.selectedId)||jd.postings?.[0],resume=s.artifacts?.resumeLab||{items:[]},cover=s.artifacts?.coverLetterLab||{questions:[]},allAssets=s.artifacts?.careerAssets?.assets||[],assets=allAssets.filter(a=>(a.evidenceLevel||legacyLevel(a.strength))!=='없음'),saved=s.artifacts?.interviewLab||{questions:[],practiceNotes:''},data=structuredClone(saved),root=document.getElementById('stepRoot');
  data.questions=data.questions||[];

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 11</div><h2>Interview Lab</h2><p>지원서에 기록한 동일한 Evidence를 말로 검증하고, JD의 핵심 질문에 일관되게 답합니다.</p></div><span class="badge">11–12주차</span></div><div class="progress"><span style="width:86%"></span></div>
    ${posting?`<div class="callout info"><b>Target</b><br>${esc(posting.company,ctx)} · ${esc(posting.jobTitle,ctx)}</div>`:''}

    <div class="block"><h3>1. Interview Risk Dashboard</h3><div id="riskDashboard">${riskDashboard(posting,resume,cover,data,ctx)}</div></div>
    <div class="hr"></div><div class="block"><h3>2. AI 예상질문 프롬프트</h3><p class="help">모범답안을 요청하지 않고, JD·이력서·자소서에서 실제로 검증해야 할 주장부터 질문하게 합니다.</p><textarea id="interviewPrompt" rows="16">${esc(buildPrompt(posting,resume,cover,assets),ctx)}</textarea><div class="actions"><button class="btn secondary" id="copyPrompt">면접 프롬프트 복사</button></div></div>

    <div class="hr"></div><div class="block"><h3>3. Question Bank</h3><div class="grid4">${sel('category','질문유형','',['인성','경험','지원동기','직무','상황','협업','갈등','실패','압박·꼬리질문','PT·발표','기타'])}${sel('sourceType','질문 출처','',['JD Evidence 질문','이력서 주장','자소서 주장','직무심층','인성·가치','기타'])}${area('question','질문','','실제 질문을 입력')}${selectAsset('assetId','답변 Evidence',assets)}</div><div id="answerEvidence" class="callout info">질문 출처와 Career Asset을 선택하면 Evidence 준비상태를 확인합니다.</div>
      <div class="grid2" style="margin-top:12px">${area('answerOutline','내 답변 구조','','결론 → 상황 → 내가 한 Action → Reasoning → Result/Evidence → 직무연결')}${area('followUps','예상 꼬리질문','','본인행동·판단이유·수치·결과를 검증할 후속질문')}${area('practice','연습 피드백','','결론 선명도 / Evidence / JD 연결 / 길이를 기준으로 기록')}${area('improve','다음 수정','','다음 연습에서 바꿀 한 가지')}</div><div class="grid2" style="margin-top:12px">${sel('answerConfidence','현재 답변 준비도','',['낮음','보통','높음'])}${sel('factCheck','사실검증','',['검증완료','추가확인 필요'])}</div><div class="actions"><button class="btn primary" id="addQuestion">질문 저장</button></div><div class="status" id="status"></div></div>

    <div class="block"><div id="questionList"></div></div>
    <div class="hr"></div><div class="block"><h3>4. 실전연습 메모</h3><textarea id="practiceNotes" rows="8" placeholder="반복해서 막힌 질문, 말이 길어진 부분, 추가로 필요한 Evidence">${esc(data.practiceNotes||'',ctx)}</textarea><div class="actions"><button class="btn primary" id="saveAll">Interview Lab 저장</button><button class="btn secondary" id="nextStep">STEP 12 Human-First Check →</button></div></div>
  </section>`;

  renderAll();['assetId','sourceType'].forEach(id=>document.getElementById(id).addEventListener('change',renderAnswerEvidence));document.getElementById('copyPrompt').addEventListener('click',()=>copy(document.getElementById('interviewPrompt').value,ctx));document.getElementById('addQuestion').addEventListener('click',addQuestion);document.getElementById('saveAll').addEventListener('click',saveAll);document.getElementById('nextStep').addEventListener('click',()=>{saveAll();ctx.navigate(12)});

  function renderAll(){renderQuestions();renderAnswerEvidence();const d=document.getElementById('riskDashboard');if(d)d.innerHTML=riskDashboard(posting,resume,cover,data,ctx)}
  function renderAnswerEvidence(){const box=document.getElementById('answerEvidence'),a=allAssets.find(x=>x.id===v('assetId')),required=evidenceRequired(v('sourceType'));if(required&&!a){box.className='callout warn';box.innerHTML='<b>Evidence 연결 필요</b><br>JD·이력서·자소서·직무심층 질문은 검증 가능한 Career Asset을 연결해야 합니다.';return;}if(!a){box.className='callout info';box.textContent='인성·가치 질문처럼 특정 경험 Evidence가 필수가 아닌 경우 비워둘 수 있습니다.';return;}const level=a.evidenceLevel||legacyLevel(a.strength),verified=isAssetVerified(a);box.className=`callout ${verified?'good':'warn'}`;box.innerHTML=`<b>${esc(level,ctx)} · ${esc(a.experienceTitle,ctx)}</b><br>Requirement: ${esc(a.requirement||'—',ctx)}<br>핵심행동: ${esc(a.proof||'—',ctx)}<br>사실 Evidence: ${esc(a.fact||'—',ctx)}<br><b>${verified?'면접 답변 Evidence 사용 가능':'최종 답변 전 Career Asset Fact Check 필요'}</b>`;}
  function addQuestion(){const q=v('question'),sourceType=v('sourceType');if(!q){status('질문을 입력하세요.');return;}if(!sourceType){status('질문 출처를 선택하세요.');return;}const assetId=v('assetId'),a=allAssets.find(x=>x.id===assetId),required=evidenceRequired(sourceType);if(required&&!assetId){status('이 질문은 답변 Evidence가 필요합니다. Career Asset을 연결하세요.');return;}if(assetId&&(a?.evidenceLevel||legacyLevel(a?.strength))==='없음'){status('Evidence 없음 자산은 답변 근거로 사용할 수 없습니다.');return;}const verified=!required||isAssetVerified(a),factCheck=v('factCheck'),ready=verified&&factCheck==='검증완료'&&!!v('answerOutline');const item={id:`iq_${Date.now()}`,category:v('category'),sourceType,question:q,assetId,answerOutline:v('answerOutline'),followUps:v('followUps'),practice:v('practice'),improve:v('improve'),answerConfidence:v('answerConfidence'),factCheck,evidenceVerified:verified,status:ready?'ready':'draft',createdAt:new Date().toISOString()};data.questions.push(item);persist();clear(['question','answerOutline','followUps','practice','improve']);document.getElementById('assetId').value='';document.getElementById('factCheck').value='';renderAll();status(ready?'검증된 Interview Answer Evidence를 저장했습니다.':'Draft로 저장했습니다. Evidence·Fact Check·답변 구조를 보완하세요.');}
  function renderQuestions(){const box=document.getElementById('questionList');if(!data.questions.length){box.innerHTML='<div class="placeholder"><b>아직 Interview Question Bank가 없습니다.</b>JD Evidence 질문과 지원서의 검증포인트부터 쌓아보세요.</div>';return;}box.innerHTML=data.questions.map((q,i)=>{const a=allAssets.find(x=>x.id===q.assetId),ready=q.status==='ready'||(q.factCheck==='검증완료'&&q.evidenceVerified&&q.answerOutline);return `<div class="listCard"><div class="listHead"><div><span class="rankTag">${esc(q.category||'질문',ctx)} ${i+1}</span><h3>${esc(q.question,ctx)}</h3><div class="muted small">${esc(q.sourceType||'출처 미분류',ctx)} · Evidence: ${esc(a?.experienceTitle||'비경험 질문',ctx)} ${a?`· ${esc(a.evidenceLevel||legacyLevel(a.strength),ctx)}`:''}</div></div>${ready?'<span class="scoreChip">Ready</span>':'<span class="scoreChip" style="background:#fff8e6;color:#9a6700;border-color:#f3dfaa">Draft</span>'}</div><div class="grid2"><div><b>답변 구조</b><p>${esc(q.answerOutline||'—',ctx)}</p></div><div><b>꼬리질문</b><p>${esc(q.followUps||'—',ctx)}</p></div><div><b>연습 피드백</b><p>${esc(q.practice||'—',ctx)}</p></div><div><b>다음 수정</b><p>${esc(q.improve||'—',ctx)}</p></div></div><div class="pillRow"><span class="pill">${esc(q.factCheck||'사실검증 미정',ctx)}</span></div><div class="actions"><button class="btn danger smallBtn" data-del="${q.id}">삭제</button></div></div>`}).join('');box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.questions=data.questions.filter(x=>x.id!==b.dataset.del);persist();renderAll();}));}
  function saveAll(){data.practiceNotes=v('practiceNotes');persist();ctx.toast('Interview Lab을 저장했습니다.');}
  function persist(){ctx.saveState({artifacts:{interviewLab:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function clear(ids){ids.forEach(id=>{const el=document.getElementById(id);if(el)el.value=''})}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}

function evidenceRequired(source=''){return ['JD Evidence 질문','이력서 주장','자소서 주장','직무심층'].includes(source)}
function isAssetVerified(a){return !!a&&a.factCheck==='검증완료'&&a.sourceExperienceFactChecked!==false}
function riskDashboard(posting,resume,cover,interview,ctx){const jdq=(posting?.requirements||[]).filter(r=>r.evidenceQuestion).length,rDraft=(resume.items||[]).filter(x=>x.status!=='final-ready'&&!(x.factChecked&&x.assetVerified)).length,cDraft=(cover.questions||[]).filter(x=>x.status!=='final-ready'&&!(x.factChecked&&x.assetVerified&&x.requirementAligned)).length,iDraft=(interview.questions||[]).filter(x=>x.status!=='ready').length,gateFail=(posting?.gates||[]).filter(x=>x.status==='미충족').length,gateCheck=(posting?.gates||[]).filter(x=>x.status==='확인 필요').length;return `<div class="grid4"><div class="miniCard"><b>Application Gate</b><span>${gateFail?`미충족 ${gateFail}`:gateCheck?`확인필요 ${gateCheck}`:posting?.gateReviewed?'검토완료':'검토필요'}</span></div><div class="miniCard"><b>JD Evidence 질문</b><span>${jdq}개</span></div><div class="miniCard"><b>지원서 Draft</b><span>Resume ${rDraft} · Cover ${cDraft}</span></div><div class="miniCard"><b>면접 Draft</b><span>${iDraft}개</span></div></div>${gateFail?'<div class="callout warn"><b>지원자격 미충족 항목이 있습니다.</b><br>면접 연습과 별도로 실제 지원 가능 여부를 먼저 확인하세요.</div>':''}`}
function buildPrompt(posting,resume,cover,assets){const jdQuestions=(posting?.requirements||[]).filter(r=>r.evidenceQuestion).map(r=>({requirement:r.text,question:r.evidenceQuestion,level:r.level})),readyResume=(resume.items||[]).filter(x=>x.status==='final-ready'||(x.factChecked&&x.assetVerified)),readyCover=(cover.questions||[]).filter(x=>x.status==='final-ready'||(x.factChecked&&x.assetVerified&&x.requirementAligned)),verifiedAssets=assets.filter(isAssetVerified);return `너는 채용면접관이다. 모범답안을 대신 써주지 말고 아래 지원서의 주장과 JD Requirement를 검증하는 실제 면접을 진행해라.\n\n[기업/직무]\n${posting?`${posting.company} / ${posting.jobTitle}`:'미등록'}\n\n[JD Evidence 질문]\n${JSON.stringify(jdQuestions,null,2)}\n\n[Final Ready 이력서]\n${JSON.stringify(readyResume,null,2)}\n\n[Final Ready 자기소개서]\n${JSON.stringify(readyCover,null,2)}\n\n[검증된 Career Asset]\n${JSON.stringify(verifiedAssets,null,2)}\n\n진행 규칙:\n1. JD Evidence 질문과 이력서·자소서의 실제 주장부터 검증한다.\n2. 한 번에 질문 하나만 한다.\n3. 답변 뒤 본인이 직접 한 Action, 판단이유, Result/Evidence를 꼬리질문한다.\n4. 이력서·자소서와 답변의 역할·기간·수치가 다르면 즉시 확인한다.\n5. 내가 말하지 않은 사실을 보완하거나 모범답안을 대신 작성하지 않는다.\n6. 모호하면 구체화를 요구한다.\n7. 매 답변 후 ① 결론 선명도 ② Evidence ③ JD 연결 ④ 지원서와의 일관성 ⑤ 길이를 피드백한다.\n8. Evidence가 약하면 억지 연결 대신 GAP라고 말한다.\n9. 압박질문은 공격이 아니라 논리·사실 재검증 방식으로 한다.\n10. 피드백 후 다음 질문으로 넘어간다.\n\n첫 질문부터 시작해줘.`}
function legacyLevel(n){return n>=5?'A · 직접 증거':n>=3?'B · 관련 증거':n>=2?'C · 간접 증거':'없음'}function selectAsset(id,label,items){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${items.map(x=>`<option value="${x.id}">[${x.evidenceLevel||legacyLevel(x.strength)}] ${x.experienceTitle} → ${x.requirement}${isAssetVerified(x)?' · ✓':' · 검증필요'}</option>`).join('')}</select></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function sel(id,label,value,opts){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${opts.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('면접 프롬프트를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
