export async function render(ctx){
  const s=ctx.getState();
  const jobs=getTargetJobs(s),ic=s.artifacts?.industryCompany||{industries:[],targetIndustries:[],companies:[],targetCompanies:[]},deep=s.artifacts?.jobDeepDive||{analyses:{}};
  const industries=(ic.targetIndustries||[]).map(id=>ic.industries?.find(x=>x.id===id)).filter(Boolean),companies=(ic.targetCompanies||[]).map(id=>ic.companies?.find(x=>x.id===id)).filter(Boolean);
  const saved=s.artifacts?.careerFit||{comparisons:[],selectedId:'',reflection:''},data=structuredClone(saved),root=document.getElementById('stepRoot');
  data.comparisons=data.comparisons||[];

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 6</div><h2>Career Fit Map</h2><p>나·직무·산업·기업을 하나의 숫자로 판정하지 않고, 선호·Evidence·정보근거를 분리해 비교합니다.</p></div><span class="badge">8주차 · 중간평가</span></div><div class="progress"><span style="width:50%"></span></div>
    <div class="callout info"><b>FIT는 ‘적성검사 점수’가 아닙니다.</b><br>여기서는 ① 내가 하고 싶은가, ② 내가 증명할 Evidence가 있는가, ③ 이 직무·산업·기업 정보를 충분히 확인했는가를 따로 봅니다. <b>최종 우선방향은 학생이 직접 선택</b>합니다.</div>

    <div class="block"><h3>1. 비교 가능한 조합 만들기</h3><p class="help">STEP 5에서 연결한 Industry ↔ Job, Company ↔ Industry ↔ Job 관계가 맞는 조합만 추가할 수 있습니다.</p>
      <div class="grid3">${selectEntity('fitJob','직무',jobs,'title')}${selectEntity('fitIndustry','산업',industries,'name')}${selectEntity('fitCompany','기업',companies,'name')}</div>
      <div id="comboGuard" class="callout info">직무·산업·기업을 선택하면 연결관계를 확인합니다.</div>
      <h4 style="margin-top:18px">A. Preference · 내가 원하는가</h4><div class="grid4">${score('roleInterest','업무 자체 관심')}${score('valueFit','가치 적합')}${score('industryAppeal','산업 관심')}${score('companyAppeal','기업 관심')}</div>
      <h4 style="margin-top:18px">B. Evidence · 내가 무엇을 증명할 수 있는가</h4><div class="grid2">${score('evidenceReadiness','현재 Evidence 준비도')}${area('evidenceReason','Evidence 근거','','관련 경험·행동·성과 중 실제로 증명 가능한 것을 적으세요.')}</div>
      <h4 style="margin-top:18px">C. Information · 이 선택을 얼마나 확인했는가</h4><div class="grid2"><div class="miniCard"><b>Job Evidence Coverage</b><span id="jobCoverage">직무 선택 후 자동 확인</span></div><div class="miniCard"><b>Industry / Company Evidence</b><span id="contextCoverage">산업·기업 선택 후 자동 확인</span></div></div>
      <div class="grid2" style="margin-top:12px">${area('fitReasons','현재 선택 근거','','Preference + Evidence + 실제 업무정보를 함께 사용해 이유를 적으세요.')}${area('fitRisks','리스크·GAP·Unknown','','부족한 경험, 정보가 없는 부분, 확인해야 할 조건')}</div>
      <div class="actions"><button class="btn primary" id="addFit">비교조합 추가</button></div><div class="status" id="status"></div>
    </div>

    <div class="block"><div id="fitList"></div></div>
    <div class="hr"></div><div class="block"><h3>2. 현재 우선방향 직접 선택</h3><p class="help">가장 높은 점수를 고르는 단계가 아닙니다. 근거와 GAP를 읽고 지금 더 깊게 탐색할 방향을 직접 선택합니다.</p><div id="priorityPick"></div></div>
    <div class="hr"></div><div class="block"><h3>3. ME × JOB × INDUSTRY × COMPANY FIT Report</h3><div class="field"><label>중간성찰</label><textarea id="reflection" placeholder="처음 생각과 비교해 무엇이 달라졌는지, 아직 무엇이 불확실한지 적어보세요.">${esc(data.reflection||'',ctx)}</textarea></div><div class="actions"><button class="btn secondary" id="buildReport">FIT Report 생성</button><button class="btn outline" id="copyReport">Report 복사</button></div><div id="reportBox" class="summaryBox" style="margin-top:14px"></div><div class="actions"><button class="btn primary" id="saveFit">중간 FIT 저장</button><button class="btn secondary" id="nextStep">STEP 7 JD Analyzer →</button></div></div>
  </section>`;

  ['fitJob','fitIndustry','fitCompany'].forEach(id=>document.getElementById(id).addEventListener('change',updateComboEvidence));
  renderList();renderPriority();renderReport();updateComboEvidence();
  document.getElementById('addFit').addEventListener('click',addFit);document.getElementById('buildReport').addEventListener('click',()=>{saveBase();renderReport();ctx.toast('FIT Report를 갱신했습니다.');});document.getElementById('copyReport').addEventListener('click',()=>copy(reportText(),ctx));document.getElementById('saveFit').addEventListener('click',()=>{saveBase();status('중간 FIT 결과를 저장했습니다.');});document.getElementById('nextStep').addEventListener('click',()=>{saveBase();ctx.navigate(7)});

  function updateComboEvidence(){const jobId=v('fitJob'),industryId=v('fitIndustry'),companyId=v('fitCompany'),guard=document.getElementById('comboGuard');const validation=validateCombo(jobId,industryId,companyId);guard.className=`callout ${validation.ok?'good':validation.level==='warn'?'warn':'info'}`;guard.innerHTML=validation.message;const jc=jobCoverage(jobId);document.getElementById('jobCoverage').textContent=jc.text;const cc=contextCoverage(industryId,companyId);document.getElementById('contextCoverage').textContent=cc.text;}
  function validateCombo(jobId,industryId,companyId){if(!jobId||!industryId||!companyId)return {ok:false,level:'info',message:'직무·산업·기업을 모두 선택하면 실제 연결관계를 검사합니다.'};const ind=industries.find(x=>x.id===industryId),co=companies.find(x=>x.id===companyId);if(ind?.jobId&&ind.jobId!==jobId)return {ok:false,level:'warn',message:`<b>조합 불일치</b><br>${esc(ind.name,ctx)}의 등록 Evidence는 다른 Target Job과 연결되어 있습니다.`};if(co?.industryId&&co.industryId!==industryId)return {ok:false,level:'warn',message:`<b>조합 불일치</b><br>${esc(co.name,ctx)}은 선택한 산업과 연결되어 있지 않습니다.`};if(co?.jobId&&co.jobId!==jobId)return {ok:false,level:'warn',message:`<b>조합 불일치</b><br>${esc(co.name,ctx)}의 등록 직무근거가 선택한 Target Job과 다릅니다.`};return {ok:true,level:'good',message:'<b>연결관계 확인</b><br>STEP 5에서 등록한 Job ↔ Industry ↔ Company 관계가 일치합니다.'};}
  function jobCoverage(jobId){const a=deep.analyses?.[jobId];if(!a)return {pct:0,text:'Job Deep Dive 분석 없음'};const src=a.sources?.length||0,tasks=a.tasks?.length||0,req=a.requirements?.length||0,pct=Math.round((Math.min(src/2,1)+Math.min(tasks/3,1)+Math.min(req/3,1))/3*100);return {pct,text:`${pct}% · 출처 ${src} · Task ${tasks} · 요구 ${req}`};}
  function contextCoverage(industryId,companyId){const ind=industries.find(x=>x.id===industryId),co=companies.find(x=>x.id===companyId);let score=0,bits=[];if(ind?.source&&ind?.url){score+=1;bits.push('산업근거 O')}else bits.push('산업근거 X');if(co?.source&&co?.url){score+=1;bits.push('기업근거 O')}else bits.push('기업근거 X');if(co?.jobUrl||['현재 채용공고 확인','최근 채용공고 확인','공식 직무소개 확인'].includes(co?.hiringEvidence)){score+=1;bits.push('직무/채용근거 O')}else bits.push('직무/채용근거 X');return {pct:Math.round(score/3*100),text:`${Math.round(score/3*100)}% · ${bits.join(' · ')}`};}
  function addFit(){const jobId=v('fitJob'),industryId=v('fitIndustry'),companyId=v('fitCompany'),validation=validateCombo(jobId,industryId,companyId);if(!jobId||!industryId||!companyId){status('직무·산업·기업을 모두 선택하세요.');return;}if(!validation.ok){status('연결되지 않은 조합입니다. STEP 5의 산업·기업 Evidence를 다시 확인하세요.');return;}const jc=jobCoverage(jobId),cc=contextCoverage(industryId,companyId);data.comparisons.push({id:`fit_${Date.now()}`,jobId,industryId,companyId,roleInterest:n('roleInterest'),valueFit:n('valueFit'),industryAppeal:n('industryAppeal'),companyAppeal:n('companyAppeal'),evidenceReadiness:n('evidenceReadiness'),evidenceReason:v('evidenceReason'),jobEvidenceCoverage:jc.pct,contextEvidenceCoverage:cc.pct,reasons:v('fitReasons'),risks:v('fitRisks'),createdAt:new Date().toISOString()});persist();renderList();renderPriority();renderReport();status('FIT 비교조합을 추가했습니다.');}
  function renderList(){const box=document.getElementById('fitList');if(!data.comparisons.length){box.innerHTML='<div class="placeholder"><b>아직 FIT 비교가 없습니다.</b>연결이 확인된 직무·산업·기업 조합을 2개 이상 비교해 보세요.</div>';return;}box.innerHTML=data.comparisons.map((x,i)=>{const z=resolve(x),pref=preference(x),jobPct=x.jobEvidenceCoverage??jobCoverage(x.jobId).pct,ctxPct=x.contextEvidenceCoverage??contextCoverage(x.industryId,x.companyId).pct;return `<div class="listCard"><div class="listHead"><div><span class="rankTag">조합 ${i+1}</span><h3>${esc(z.job,ctx)} × ${esc(z.industry,ctx)} × ${esc(z.company,ctx)}</h3></div><span class="badge">판단 후보</span></div><div class="grid3"><div class="miniCard"><b>Preference</b><span>${pref.toFixed(1)}/5 · 업무·가치·산업·기업 관심의 자기평가</span></div><div class="miniCard"><b>My Evidence</b><span>${x.evidenceReadiness||0}/5 · ${esc(x.evidenceReason||'근거 미작성',ctx)}</span></div><div class="miniCard"><b>Information</b><span>직무 ${jobPct}% · 산업/기업 ${ctxPct}%</span></div></div><div class="grid2" style="margin-top:10px"><div><b>현재 선택 근거</b><p>${esc(x.reasons||'—',ctx)}</p></div><div><b>리스크·GAP·Unknown</b><p>${esc(x.risks||'—',ctx)}</p></div></div><div class="actions"><button class="btn danger smallBtn" data-del="${x.id}">삭제</button></div></div>`}).join('');box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.comparisons=data.comparisons.filter(x=>x.id!==b.dataset.del);if(data.selectedId===b.dataset.del)data.selectedId='';persist();renderList();renderPriority();renderReport();}));}
  function renderPriority(){const box=document.getElementById('priorityPick');if(!data.comparisons.length){box.innerHTML='<div class="callout warn">비교조합을 먼저 만드세요.</div>';return;}box.innerHTML=data.comparisons.map(x=>{const z=resolve(x);return `<label class="checkRow"><input type="radio" name="priority" value="${x.id}" ${data.selectedId===x.id?'checked':''}><div><b>${esc(z.job,ctx)} × ${esc(z.industry,ctx)} × ${esc(z.company,ctx)}</b><span>Preference ${preference(x).toFixed(1)}/5 · Evidence ${x.evidenceReadiness||0}/5 · 정보근거는 별도 확인</span></div></label>`}).join('');box.querySelectorAll('input[name=priority]').forEach(r=>r.addEventListener('change',()=>{data.selectedId=r.value;persist();renderReport();}));}
  function renderReport(){document.getElementById('reportBox').innerHTML=`<h4>중간 Career FIT Report</h4><pre style="white-space:pre-wrap;margin:0;font-family:inherit;line-height:1.65;color:#475467">${esc(reportText(),ctx)}</pre>`}
  function reportText(){const selected=data.comparisons.find(x=>x.id===data.selectedId),lines=['ME × JOB × INDUSTRY × COMPANY FIT REPORT','','[1. 나의 현재 Career Evidence]',summarySelf(s),'','[2. 비교한 방향]'];if(!data.comparisons.length)lines.push('아직 비교조합 없음');else data.comparisons.forEach((x,i)=>{const z=resolve(x),jc=x.jobEvidenceCoverage??jobCoverage(x.jobId).pct,cc=x.contextEvidenceCoverage??contextCoverage(x.industryId,x.companyId).pct;lines.push(`${i+1}) ${z.job} × ${z.industry} × ${z.company}`);lines.push(`   Preference: ${preference(x).toFixed(1)}/5 | My Evidence: ${x.evidenceReadiness||0}/5 | 정보근거: Job ${jc}% / Context ${cc}%`);lines.push(`   Evidence 근거: ${x.evidenceReason||'미작성'}`);lines.push(`   선택 근거: ${x.reasons||'미작성'}`);lines.push(`   GAP/Unknown: ${x.risks||'미작성'}`)});lines.push('','[3. 내가 직접 선택한 현재 우선방향]');if(selected){const z=resolve(selected);lines.push(`${z.job} × ${z.industry} × ${z.company}`,`선택 근거: ${selected.reasons||'추가 작성 필요'}`,`확인할 GAP: ${selected.risks||'추가 작성 필요'}`)}else lines.push('아직 선택하지 않음');lines.push('','[4. 중간성찰]',document.getElementById('reflection')?.value?.trim()||data.reflection||'미작성','','※ FIT는 타당화된 심리검사 점수나 취업가능성 예측값이 아닙니다. Preference, Evidence, Information을 구분하여 진로탐색 의사결정을 지원하는 학습도구입니다.');return lines.join('\n');}
  function resolve(x){return {job:jobs.find(j=>j.id===x.jobId)?.title||'직무 미확인',industry:industries.find(i=>i.id===x.industryId)?.name||'산업 미확인',company:companies.find(c=>c.id===x.companyId)?.name||'기업 미확인'}}function preference(x){return [x.roleInterest,x.valueFit,x.industryAppeal,x.companyAppeal].reduce((a,b)=>a+(+b||0),0)/4}function saveBase(){data.reflection=v('reflection');persist()}function persist(){ctx.saveState({artifacts:{careerFit:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function n(id){return Number(document.getElementById(id)?.value||0)}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}

function summarySelf(s){const d=s.assessments?.careerDNA||{},ex=s.assessments?.experienceCompetency?.experiences||[],bits=[];if(d.interest?.type)bits.push(`직업선호도: ${d.interest.type}형`);const r=d.interest?.riasecStandard||d.interest?.riasecRaw||{},top=Object.entries(r).filter(([,v])=>Number.isFinite(v)).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k,v])=>`${k} ${v}`).join(', ');if(top)bits.push(`RIASEC: ${top}`);const vals=Object.entries(d.workValues||{}).filter(([,v])=>Number.isFinite(v)).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k])=>k);if(vals.length)bits.push(`직업가치: ${vals.join(', ')}`);const comps=[...new Set(ex.flatMap(x=>x.competencies||[]))].slice(0,8);if(comps.length)bits.push(`경험기반 역량: ${comps.join(', ')}`);return bits.join('\n')||'Career DNA와 Experience Evidence를 추가로 입력하세요.'}
function getTargetJobs(s){const e=s.artifacts?.jobExplorer||{};return (e.targets||[]).map(id=>e.candidates?.find(x=>x.id===id)).filter(Boolean)}function selectEntity(id,label,items,key){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${items.map(x=>`<option value="${x.id}">${x[key]}</option>`).join('')}</select></div>`}function score(id,label){return `<div class="field"><label>${label} <span class="muted">1–5</span></label><select id="${id}"><option value="1">1 낮음</option><option value="2">2</option><option value="3" selected>3 보통</option><option value="4">4</option><option value="5">5 높음</option></select></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('FIT Report를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
