export async function render(ctx){
  const s=ctx.getState(),jd=s.artifacts?.jdAnalyzer||{postings:[],selectedId:''},posting=jd.postings?.find(x=>x.id===jd.selectedId)||jd.postings?.[0],assets=s.artifacts?.careerAssets?.assets||[],candidateAssets=assets.filter(a=>(a.evidenceLevel||legacyLevel(a.strength))!=='없음'),saved=s.artifacts?.resumeLab||{items:[],summary:'',skills:'',notes:''},data=structuredClone(saved),root=document.getElementById('stepRoot');
  data.items=data.items||[];

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 9</div><h2>Resume Lab</h2><p>JD와 Career Asset을 연결해 이력서·경험기술서를 만들되, 검증된 사실만 최종 문장으로 사용합니다.</p></div><span class="badge">9주차</span></div><div class="progress"><span style="width:71%"></span></div>
    ${posting?`<div class="callout info"><b>Target JD</b><br>${esc(posting.company,ctx)} · ${esc(posting.jobTitle,ctx)}</div>`:''}
    ${posting?gateNotice(posting,ctx):''}

    <div class="block"><h3>1. Resume Evidence Gate</h3><div id="resumeGate"></div><div class="grid3" style="margin-top:12px"><div class="miniCard"><b>Fact</b><span>하지 않은 일·없는 수치를 쓰지 않는다.</span></div><div class="miniCard"><b>Action</b><span>역할명이 아니라 내가 직접 한 행동을 쓴다.</span></div><div class="miniCard"><b>Evidence</b><span>JD Requirement를 증명하는 Career Asset만 사용한다.</span></div></div></div>

    <div class="hr"></div><div class="block"><h3>2. Career Asset → Resume Bullet</h3><p class="help">Fact Check가 끝나지 않은 자산도 초안 연습은 가능하지만, 최종 제출용으로는 표시하지 않습니다.</p><div class="grid2">${selectAsset('assetId','Career Asset',candidateAssets)}${sel('section','이력서 섹션','',['프로젝트','인턴·경력','대외활동','아르바이트','교육·수업','기타'])}</div><div id="assetContext" class="callout info">Career Asset을 선택하면 Evidence와 검증상태를 확인합니다.</div>
      <div class="grid2" style="margin-top:12px">${area('rawBullet','내 원문','','내가 먼저 사실 중심으로 작성한 문장')}${area('aiBullet','AI 구조화','','AI가 제안한 문장 또는 구조')}${area('finalBullet','최종 Bullet','','Action + 대상/방법 + Result/Evidence 중심으로 최종 수정')}${area('detailText','경험기술서 확장','','필요 시 3~5문장으로 역할·행동·성과를 확장')}</div>
      <label class="checkRow"><input type="checkbox" id="factChecked"><div><b>Resume Fact Check</b><span>행동·수치·결과가 Career Asset 및 원경험의 사실과 일치합니다.</span></div></label>
      <div class="actions"><button class="btn secondary" id="copyPrompt">Resume AI 프롬프트 복사</button><button class="btn primary" id="addItem">이력서 문장 추가</button></div><div class="status" id="status"></div>
    </div>

    <div class="block"><div id="resumeItems"></div></div>
    <div class="hr"></div><div class="block"><h3>3. 직무맞춤 요약</h3><div class="grid2">${area('summary','직무 요약',data.summary,'내가 어떤 Evidence를 가진 지원자인지 2~3문장')}${area('skills','직무 관련 Skill·Tool',data.skills,'JD에서 실제로 요구하고 내가 보유한 Skill·Tool만')}</div><div class="field" style="margin-top:12px"><label>점검 메모</label><textarea id="notes" placeholder="추가 보완할 부분">${esc(data.notes||'',ctx)}</textarea></div><div class="actions"><button class="btn primary" id="saveResume">Resume 저장</button><button class="btn secondary" id="nextStep">STEP 10 Cover Letter Lab →</button></div></div>
  </section>`;

  renderAll();document.getElementById('assetId').addEventListener('change',renderAssetContext);document.getElementById('copyPrompt').addEventListener('click',()=>copy(buildPrompt(),ctx));document.getElementById('addItem').addEventListener('click',addItem);document.getElementById('saveResume').addEventListener('click',saveBase);document.getElementById('nextStep').addEventListener('click',()=>{saveBase();ctx.navigate(10)});

  function renderAll(){renderGate();renderItems();renderAssetContext();}
  function renderGate(){const box=document.getElementById('resumeGate');if(!box)return;const verified=candidateAssets.filter(isAssetVerified).length,draft=candidateAssets.length-verified,finalItems=data.items.filter(x=>x.factChecked&&x.assetVerified).length,draftItems=data.items.length-finalItems;box.innerHTML=`<div class="grid4"><div class="miniCard"><b>Career Asset 후보</b><span>${candidateAssets.length}개</span></div><div class="miniCard"><b>검증된 Asset</b><span>${verified}개</span></div><div class="miniCard"><b>검증대기 Asset</b><span>${draft}개</span></div><div class="miniCard"><b>최종 사용 가능 Bullet</b><span>${finalItems}개 · 초안 ${draftItems}개</span></div></div>${draft?'<div class="callout warn"><b>검증대기 Career Asset이 있습니다.</b><br>초안 작성은 가능하지만 최종 Resume에는 Career Asset Fact Check와 원경험 Fact Check를 모두 완료한 항목만 사용하세요.</div>':'<div class="callout good"><b>Career Asset 검증상태 양호</b><br>현재 선택 가능한 자산은 사실검증 상태가 확인되었습니다.</div>'}`;}
  function renderAssetContext(){const box=document.getElementById('assetContext'),a=assets.find(x=>x.id===v('assetId'));if(!a){box.className='callout info';box.textContent=candidateAssets.length?'Career Asset을 선택하세요.':'사용 가능한 Career Asset이 없습니다. STEP 8에서 JD Requirement와 Evidence를 먼저 연결하세요.';return;}const level=a.evidenceLevel||legacyLevel(a.strength),verified=isAssetVerified(a);box.className=`callout ${verified?'good':'warn'}`;box.innerHTML=`<b>${esc(level,ctx)} · ${esc(a.experienceTitle,ctx)} → ${esc(a.requirement,ctx)}</b><br>Career Asset 사실검증: ${esc(a.factCheck||'미확인',ctx)}${a.sourceExperienceFactChecked===false?' · 원경험 Fact Check 미완료':''}<br>핵심행동: ${esc(a.proof||'미입력',ctx)}<br>Evidence: ${esc(a.fact||'미입력',ctx)}<br><b>${verified?'최종 Resume 사용 가능':'현재는 초안용 · 검증 후 최종 사용'}</b>`;}
  function addItem(){const assetId=v('assetId');if(!assetId){status('Career Asset을 선택하세요.');return;}const a=assets.find(x=>x.id===assetId),level=a?.evidenceLevel||legacyLevel(a?.strength);if(level==='없음'){status('Evidence 없음 자산은 Resume에 사용할 수 없습니다.');return;}if(!v('rawBullet')&&!v('finalBullet')&&!v('aiBullet')){status('최소한 내 원문 또는 최종 Bullet을 작성하세요.');return;}const assetVerified=isAssetVerified(a),resumeChecked=document.getElementById('factChecked').checked,item={id:`resume_${Date.now()}`,assetId,assetTitle:a?.experienceTitle||'',requirement:a?.requirement||'',requirementLevel:a?.requirementLevel||'',evidenceLevel:level,assetFactCheck:a?.factCheck||'',assetVerified,section:v('section'),rawBullet:v('rawBullet'),aiBullet:v('aiBullet'),finalBullet:v('finalBullet'),detailText:v('detailText'),factChecked:resumeChecked,status:assetVerified&&resumeChecked?'final-ready':'draft'};data.items.push(item);persist();['rawBullet','aiBullet','finalBullet','detailText'].forEach(id=>document.getElementById(id).value='');document.getElementById('factChecked').checked=false;renderAll();status(item.status==='final-ready'?'최종 사용 가능한 Resume 문장을 추가했습니다.':'초안으로 저장했습니다. 사실검증 후 최종 사용하세요.');}
  function renderItems(){const box=document.getElementById('resumeItems');if(!data.items.length){box.innerHTML='<div class="placeholder"><b>아직 Resume 문장이 없습니다.</b>Career Asset을 실제 이력서 문장으로 바꾸세요.</div>';return;}box.innerHTML=data.items.map((x,i)=>{const ready=x.status==='final-ready'||(x.factChecked&&x.assetVerified);return `<div class="listCard"><div class="listHead"><div><span class="rankTag">Resume ${i+1}</span><h3>${esc(x.assetTitle,ctx)}</h3><div class="muted small">${esc(x.section||'섹션 미정',ctx)} · ${esc(x.evidenceLevel||'',ctx)} · ${esc(x.requirementLevel||'중요도 미분류',ctx)}</div></div>${ready?'<span class="scoreChip">Final Ready</span>':'<span class="scoreChip" style="background:#fff8e6;color:#9a6700;border-color:#f3dfaa">Draft · 검증필요</span>'}</div><div><b>연결 Requirement</b><p>${esc(x.requirement||'—',ctx)}</p></div><div><b>최종 Bullet</b><p>${esc(x.finalBullet||x.aiBullet||x.rawBullet||'—',ctx)}</p></div>${x.detailText?`<div><b>경험기술</b><p>${esc(x.detailText,ctx)}</p></div>`:''}<div class="actions"><button class="btn danger smallBtn" data-del="${x.id}">삭제</button></div></div>`}).join('');box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.items=data.items.filter(x=>x.id!==b.dataset.del);persist();renderAll();}));}
  function buildPrompt(){const a=assets.find(x=>x.id===v('assetId'));return `너는 이력서 문장 코치다. 아래 Career Asset에 기록된 사실만 사용해 Resume bullet을 구조화해라. 없는 숫자·성과·역할은 만들지 마라.\n\n[Target JD]\n${posting?`${posting.company} / ${posting.jobTitle}\n${posting.rawPosting||''}`:'미등록'}\n\n[Career Asset]\n${JSON.stringify(a||{},null,2)}\n\n[내가 먼저 쓴 문장]\n${v('rawBullet')||'미작성'}\n\n규칙:\n1. Career Asset의 Evidence 수준이 '없음'이면 문장을 만들지 말고 GAP라고 알려라.\n2. Career Asset 또는 원경험 Fact Check가 미완료이면 결과를 '초안'이라고 명시해라.\n3. 내가 직접 한 Action이 앞에 드러나게 한다.\n4. 대상·방법·결과·Evidence 중 실제 존재하는 정보만 사용한다.\n5. 수치가 없으면 만들지 않는다.\n6. JD 키워드를 억지로 삽입하지 않는다.\n7. 1줄 Bullet 2안과 경험기술서용 3~4문장 1안을 제시한다.\n8. 원문보다 과장된 표현과 사실확인이 필요한 표현을 마지막에 따로 표시한다.`}
  function saveBase(){data.summary=v('summary');data.skills=v('skills');data.notes=v('notes');persist();ctx.toast('Resume Lab 결과를 저장했습니다.');}
  function persist(){ctx.saveState({artifacts:{resumeLab:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}
function gateNotice(p,ctx){const fail=(p.gates||[]).filter(x=>x.status==='미충족'),check=(p.gates||[]).filter(x=>x.status==='확인 필요');if(fail.length)return `<div class="callout warn"><b>Application Gate 미충족</b><br>${fail.map(x=>esc(x.text,ctx)).join(' · ')}<br>이력서 작성과 별개로 지원자격 충족 여부를 먼저 확인하세요.</div>`;if(check.length||!p.gateReviewed)return '<div class="callout info"><b>지원자격 확인 미완료</b><br>Resume를 작성할 수는 있지만 실제 지원 전 STEP 7 Application Gate를 반드시 확인하세요.</div>';return ''}
function isAssetVerified(a){return !!a&&a.factCheck==='검증완료'&&a.sourceExperienceFactChecked!==false}
function legacyLevel(n){return n>=5?'A · 직접 증거':n>=3?'B · 관련 증거':n>=2?'C · 간접 증거':'없음'}function selectAsset(id,label,items){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${items.map(x=>`<option value="${x.id}">[${x.evidenceLevel||legacyLevel(x.strength)}] ${x.experienceTitle} → ${x.requirement}${isAssetVerified(x)?' · ✓':' · 검증필요'}</option>`).join('')}</select></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function sel(id,label,value,opts){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${opts.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('Resume 프롬프트를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
