export async function render(ctx){
  const s=ctx.getState(),experiences=s.assessments?.experienceCompetency?.experiences||[],assets=s.artifacts?.careerAssets?.assets||[],cover=s.artifacts?.coverLetterLab||{questions:[]},resume=s.artifacts?.resumeLab||{items:[]},interview=s.artifacts?.interviewLab||{questions:[]},jd=s.artifacts?.jdAnalyzer||{postings:[],selectedId:''},posting=jd.postings?.find(x=>x.id===jd.selectedId)||jd.postings?.[0],saved=s.artifacts?.humanFirst||{items:[],consistency:{resumeCover:false,coverInterview:false,factLock:false},notes:''},data=structuredClone(saved),root=document.getElementById('stepRoot');
  data.items=data.items||[];data.consistency=data.consistency||{resumeCover:false,coverInterview:false,factLock:false};

  root.innerHTML=`<section class="card">
    <div class="sectionHead"><div><div class="kicker">STEP 12</div><h2>Human-First Check</h2><p>AI 문장을 꾸미는 단계가 아니라, 지원자격·Evidence·지원서·면접의 Fact Chain을 잠그고 실제 학생의 언어로 최종 정리합니다.</p></div><span class="badge">13주차</span></div><div class="progress"><span style="width:93%"></span></div>
    <div class="callout info"><b>목표는 AI 탐지 우회가 아닙니다.</b><br>실제 경험·Evidence·전문성을 보존하고, 과장·번역투·상투표현을 제거해 <b>본인이 면접에서 그대로 설명할 수 있는 문장</b>으로 만듭니다.</div>

    <div class="block"><h3>1. Final Evidence Chain Dashboard</h3><div id="chainDashboard">${chainDashboard(posting,resume,cover,interview,data,ctx)}</div></div>
    <div class="hr"></div><div class="block"><h3>2. My Raw Voice</h3><p class="help">STEP 2에서 남긴 원래 표현입니다. AI가 다듬기 전 내가 실제로 설명한 언어를 참고합니다.</p><div class="resultGrid">${rawVoiceCards(experiences,ctx)}</div></div>

    <div class="hr"></div><div class="block"><h3>3. 자기소개서 문장 Human-First 편집</h3>${selectQuestion('coverId','수정할 자소서 문항',cover.questions||[])}<div class="actions"><button class="btn secondary" id="loadDraft">초안·Evidence 불러오기</button><button class="btn outline" id="copyPrompt">Human-First 프롬프트 복사</button></div><div id="sourceEvidence" class="callout info">자소서 문항을 선택하면 Cover 상태·Career Asset·Raw Voice를 표시합니다.</div>
      <div class="field" style="margin-top:12px"><label>AI 초안</label><textarea id="draft" rows="9" placeholder="수정할 초안을 불러오거나 붙여넣으세요."></textarea></div><div class="grid3" style="margin-top:12px">${area('keep','KEEP','','구체적이고 사실적이라 그대로 둘 부분')}${area('humanize','HUMANIZE','','내용은 필요하지만 내 말 같지 않은 부분')}${area('deleteText','DELETE','','정보가 없거나 상투적인 부분')}</div><div class="field" style="margin-top:12px"><label>My Voice 최종본</label><textarea id="finalText" rows="10" placeholder="학생이 직접 확인·수정한 최종 문장"></textarea></div><label class="checkRow"><input type="checkbox" id="factChecked"><div><b>Human-First Fact Lock</b><span>숫자·행동·역할·결과가 연결된 Career Asset과 일치하며 새 사실을 추가하지 않았습니다.</span></div></label><div class="actions"><button class="btn primary" id="saveHuman">Human-First 버전 저장</button></div><div class="status" id="status"></div></div>

    <div class="block"><div id="humanList"></div></div>
    <div class="hr"></div><div class="block"><h3>4. 지원서 ↔ 면접 일관성 검증</h3>${check('resumeCover','이력서와 자기소개서의 역할·기간·수치가 서로 일치한다.',data.consistency.resumeCover)}${check('coverInterview','자기소개서에서 강조한 경험을 면접에서 내 말로 설명할 수 있다.',data.consistency.coverInterview)}${check('factLockAll','이력서·자소서·면접 어디에도 새로 만들어진 사실이 없다.',data.consistency.factLock)}<div id="finalGuard" style="margin-top:10px">${finalGuardHtml(posting,resume,cover,interview,data,ctx)}</div><div class="field" style="margin-top:12px"><label>최종 점검 메모</label><textarea id="notes" placeholder="아직 어색한 표현, 면접에서 설명하기 어려운 부분, 수정할 사실">${esc(data.notes||'',ctx)}</textarea></div><div class="actions"><button class="btn primary" id="saveAll">Human-First Check 저장</button><button class="btn secondary" id="nextStep">STEP 13 AI Job Portfolio →</button></div></div>
  </section>`;

  renderAll();document.getElementById('coverId').addEventListener('change',renderSourceEvidence);document.getElementById('loadDraft').addEventListener('click',loadDraft);document.getElementById('copyPrompt').addEventListener('click',()=>copy(buildPrompt(),ctx));document.getElementById('saveHuman').addEventListener('click',saveHuman);document.getElementById('saveAll').addEventListener('click',saveAll);document.getElementById('nextStep').addEventListener('click',()=>{saveAll();ctx.navigate(13)});

  function renderAll(){renderHumanList();renderSourceEvidence();refreshGuards()}
  function selectedCover(){return cover.questions?.find(x=>x.id===v('coverId'))}
  function linkedAssets(q=selectedCover()){return (q?.assetIds||[]).map(id=>assets.find(a=>a.id===id)).filter(Boolean)}
  function linkedExperiences(q=selectedCover()){const ids=new Set(linkedAssets(q).map(a=>a.experienceId));return experiences.filter(e=>ids.has(e.id))}
  function renderSourceEvidence(){const box=document.getElementById('sourceEvidence'),q=selectedCover();if(!box)return;if(!q){box.className='callout info';box.textContent='자소서 문항을 선택하면 Cover 상태·Career Asset·Raw Voice를 표시합니다.';return;}const aa=linkedAssets(q),ee=linkedExperiences(q),weak=aa.filter(a=>!isAssetVerified(a)),coverReady=isCoverReady(q);box.className=`callout ${coverReady&&!weak.length?'good':'warn'}`;box.innerHTML=`<b>Cover Letter 상태</b>: ${coverReady?'Final Ready':'Draft / 검증필요'}<br><b>연결 Evidence</b>: ${aa.length?aa.map(a=>`${esc(a.experienceTitle,ctx)} (${esc(a.evidenceLevel||legacyLevel(a.strength),ctx)})`).join(' · '):'없음'}<br><b>Raw Voice</b>: ${ee.map(e=>esc(e.rawVoice||'',ctx)).filter(Boolean).join(' / ')||'미입력'}${weak.length?'<br><b>주의</b>: 연결 Career Asset 중 Fact Check 미완료 항목이 있습니다.':''}${!coverReady?'<br><b>주의</b>: STEP 10 문항의 Requirement 연결 또는 Fact Check가 아직 완료되지 않았습니다.':''}`;}
  function loadDraft(){const q=selectedCover();document.getElementById('draft').value=q?.draft||'';renderSourceEvidence();ctx.toast(q?.draft?'초안을 불러왔습니다.':'저장된 초안이 없습니다.');}
  function saveHuman(){const coverId=v('coverId'),draft=v('draft'),finalText=v('finalText'),q=selectedCover();if(!coverId){status('자소서 문항을 선택하세요.');return;}if(!finalText){status('My Voice 최종본을 작성하세요.');return;}const aa=linkedAssets(q),assetsVerified=aa.length>0&&aa.every(isAssetVerified),coverReady=isCoverReady(q),factChecked=document.getElementById('factChecked').checked,ready=coverReady&&assetsVerified&&factChecked;const item={id:`hf_${Date.now()}`,coverId,question:q?.question||'',sourceAssetIds:aa.map(a=>a.id),draft,keep:v('keep'),humanize:v('humanize'),deleteText:v('deleteText'),finalText,factChecked,coverReady,assetsVerified,status:ready?'final-ready':'draft',createdAt:new Date().toISOString()};data.items=data.items.filter(x=>x.coverId!==coverId);data.items.push(item);persist();renderAll();status(ready?'Human-First Final Ready 버전을 저장했습니다.':'Human-First Draft로 저장했습니다. 이전 Evidence Chain과 Fact Lock을 확인하세요.');}
  function renderHumanList(){const box=document.getElementById('humanList');if(!data.items.length){box.innerHTML='<div class="placeholder"><b>아직 Human-First 최종본이 없습니다.</b>AI 초안과 연결 Evidence·Raw Voice를 비교해 한 문항씩 최종확정하세요.</div>';return;}box.innerHTML=data.items.map((x,i)=>{const ready=x.status==='final-ready'||(x.factChecked&&x.coverReady&&x.assetsVerified);return `<div class="listCard"><div class="listHead"><div><span class="rankTag">Final ${i+1}</span><h3>${esc(x.question||'자소서 문항',ctx)}</h3></div>${ready?'<span class="scoreChip">Final Ready</span>':'<span class="scoreChip" style="background:#fff8e6;color:#9a6700;border-color:#f3dfaa">Draft · 확인 필요</span>'}</div><div><b>My Voice 최종본</b><p>${esc(x.finalText||'—',ctx)}</p></div><div class="actions"><button class="btn danger smallBtn" data-del="${x.id}">삭제</button></div></div>`}).join('');box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{data.items=data.items.filter(x=>x.id!==b.dataset.del);persist();renderAll();}));}
  function saveAll(){data.consistency={resumeCover:document.getElementById('resumeCover').checked,coverInterview:document.getElementById('coverInterview').checked,factLock:document.getElementById('factLockAll').checked};data.notes=v('notes');persist();refreshGuards();ctx.toast('Human-First Check를 저장했습니다.');}
  function refreshGuards(){const d=document.getElementById('chainDashboard'),g=document.getElementById('finalGuard');if(d)d.innerHTML=chainDashboard(posting,resume,cover,interview,data,ctx);if(g)g.innerHTML=finalGuardHtml(posting,resume,cover,interview,data,ctx)}
  function buildPrompt(){const q=selectedCover(),aa=linkedAssets(q),ee=linkedExperiences(q);return `너는 AI 탐지 우회 도구가 아니라 지원자의 실제 언어와 사실을 회복하는 편집자다.\n\n[자기소개서 문항]\n${q?.question||'미선택'}\n\n[문항 상태]\n${q?.status||'미확인'}\n\n[연결된 Career Asset]\n${JSON.stringify(aa,null,2)}\n\n[해당 경험의 Raw Voice]\n${JSON.stringify(ee.map(e=>({title:e.title,rawVoice:e.rawVoice})),null,2)}\n\n[수정할 초안]\n${v('draft')||'미입력'}\n\n문장별로 KEEP / HUMANIZE / DELETE로 분류해라.\nKEEP: 구체적이고 사실적이며 Evidence와 일치\nHUMANIZE: 내용은 필요하지만 번역투·추상어·과도한 수식 때문에 실제 지원자의 언어와 거리 있음\nDELETE: 새로운 정보가 없거나 누구에게나 적용되는 일반론\n\n규칙:\n1. Career Asset의 숫자·행동·역할·결과를 절대 바꾸지 않는다.\n2. 연결 Evidence에 없는 새로운 사실을 추가하지 않는다.\n3. STEP 10에서 Draft 상태인 문항은 표현을 다듬기 전에 왜 Draft인지 먼저 알려준다.\n4. 원문에 없는 역량·성과를 더 좋아 보이게 보충하지 않는다.\n5. 문법을 일부러 틀리거나 AI 탐지 회피 패턴을 만들지 않는다.\n6. Raw Voice에 없는 말투를 억지로 흉내내지 않는다.\n7. 최소변경을 우선한다.\n8. 면접에서 그대로 설명하기 어려운 표현을 표시한다.\n9. 마지막에 Fact Check가 필요한 표현을 별도 목록으로 제시한다.\n\n먼저 KEEP / HUMANIZE / DELETE 표부터 보여줘.`}
  function persist(){ctx.saveState({artifacts:{humanFirst:data}})}function v(id){return document.getElementById(id)?.value?.trim()||''}function status(t){document.getElementById('status').textContent=t;ctx.toast(t)}
}

function isAssetVerified(a){return !!a&&a.factCheck==='검증완료'&&a.sourceExperienceFactChecked!==false}
function isResumeReady(x){return x.status==='final-ready'||(x.factChecked&&x.assetVerified)}function isCoverReady(x){return x.status==='final-ready'||(x.factChecked&&x.assetVerified&&x.requirementAligned)}function isInterviewReady(x){return x.status==='ready'||(x.factCheck==='검증완료'&&x.evidenceVerified&&x.answerOutline)}function isHumanReady(x){return x.status==='final-ready'||(x.factChecked&&x.coverReady&&x.assetsVerified)}
function gateState(p){const fail=(p?.gates||[]).filter(x=>x.status==='미충족').length,check=(p?.gates||[]).filter(x=>x.status==='확인 필요').length;return {fail,check,ready:!!p?.gateReviewed&&!fail&&!check}}
function chainDashboard(posting,resume,cover,interview,data,ctx){const gate=gateState(posting),r=(resume.items||[]).filter(x=>!isResumeReady(x)).length,c=(cover.questions||[]).filter(x=>!isCoverReady(x)).length,i=(interview.questions||[]).filter(x=>!isInterviewReady(x)).length,h=(data.items||[]).filter(x=>!isHumanReady(x)).length;return `<div class="grid4"><div class="miniCard"><b>Application Gate</b><span>${gate.fail?`미충족 ${gate.fail}`:gate.check?`확인필요 ${gate.check}`:gate.ready?'확인완료':'검토필요'}</span></div><div class="miniCard"><b>Resume Draft</b><span>${r}개</span></div><div class="miniCard"><b>Cover / Interview Draft</b><span>${c} / ${i}개</span></div><div class="miniCard"><b>Human-First Draft</b><span>${h}개</span></div></div>`}
function finalGuardHtml(posting,resume,cover,interview,data,ctx){const issues=[],gate=gateState(posting);if(gate.fail)issues.push(`Application Gate 미충족 ${gate.fail}개`);if(gate.check)issues.push(`Application Gate 확인필요 ${gate.check}개`);if(!posting?.gateReviewed)issues.push('Application Gate 원문대조 미완료');(resume.items||[]).forEach(x=>{if(!isResumeReady(x))issues.push(`Resume: ${x.assetTitle||'항목'}`)});(cover.questions||[]).forEach((x,i)=>{if(!isCoverReady(x))issues.push(`자소서 문항 ${i+1}`)});(interview.questions||[]).forEach((x,i)=>{if(!isInterviewReady(x))issues.push(`면접질문 ${i+1}`)});(data.items||[]).forEach((x,i)=>{if(!isHumanReady(x))issues.push(`Human-First ${i+1}`)});const cons=data.consistency||{};if(!cons.resumeCover)issues.push('이력서↔자소서 일관성 미확인');if(!cons.coverInterview)issues.push('자소서↔면접 일관성 미확인');if(!cons.factLock)issues.push('전체 Fact Lock 미확인');return issues.length?`<div class="callout warn"><b>Portfolio Final Ready 전 확인할 항목 ${issues.length}개</b><br>${issues.slice(0,12).map(x=>esc(x,ctx)).join(' · ')}</div>`:'<div class="callout good"><b>Final Evidence Chain 확인</b><br>지원자격·이력서·자소서·면접·Human-First와 전체 Fact Lock 상태가 연결되어 있습니다. 최종 제출 전 원자료를 한 번 더 대조하세요.</div>'}
function rawVoiceCards(items,ctx){const rows=items.filter(x=>x.rawVoice).slice(0,8);if(!rows.length)return '<div class="placeholder"><b>Raw Voice가 없습니다.</b>STEP 2의 경험에서 본인이 실제로 설명한 표현을 남기면 여기에서 활용할 수 있습니다.</div>';return rows.map(x=>`<div class="resultCard"><strong>${ctx.escapeHtml(x.title)}</strong><p>${ctx.escapeHtml(x.rawVoice)}</p></div>`).join('')}
function legacyLevel(n){return n>=5?'A · 직접 증거':n>=3?'B · 관련 증거':n>=2?'C · 간접 증거':'없음'}function selectQuestion(id,label,items){return `<div class="field"><label>${label}</label><select id="${id}"><option value="">선택</option>${items.map(x=>`<option value="${x.id}">${x.question}${isCoverReady(x)?' · Final Ready':' · Draft'}</option>`).join('')}</select></div>`}function area(id,label,value,ph){return `<div class="field"><label>${label}</label><textarea id="${id}" placeholder="${ph||''}">${value||''}</textarea></div>`}function check(id,text,on){return `<label class="checkRow"><input type="checkbox" id="${id}" ${on?'checked':''}><div><b>${text}</b></div></label>`}function esc(x,ctx){return ctx.escapeHtml(x==null?'':x)}async function copy(t,ctx){try{await navigator.clipboard.writeText(t);ctx.toast('Human-First 프롬프트를 복사했습니다.')}catch{ctx.toast('복사하지 못했습니다.')}}
